删除李赋的部分内容
project-trans/MtF-wiki pull request #1007
Opened 2024-04-10 03:03 UTC by Hatsushigure

已确认李赋目前只看周五下午

2024-04-10 03:24 UTC, BeiyanYunyi approved these changes

2024-04-10 05:30 UTC, AnnaBeiyan commented
请求确认是周六不开证还是完全不给看跨性别

2024-04-10 13:05 UTC, Hatsushigure commented
> 请求确认是周六不开证还是完全不给看跨性别

周六根本没号，不看

2024-04-10 13:12 UTC, Hatsushigure commented
> > 请求确认是周六不开证还是完全不给看跨性别
> 
> 周六根本没号，不看

刚才确认李赋周二在六角亭院区有心理咨询门诊，但不知道开不开证

2024-04-10 13:22 UTC, AnnaBeiyan commented
那要不加上周六出诊然后把最后均可开证删掉？

2024-04-10 18:47 UTC, Cryolitia commented
> 那要不加上周六出诊然后把最后均可开证删掉？

说的是周二不是周六（

2024-04-10 22:17 UTC, Hatsushigure commented
李赋在六角亭是周二下午的号，听一个去过六角亭的朋友说那边下午似乎做不了量表，所以可能是开不了证的

2024-04-10 23:41 UTC, Cryolitia commented
建议改成

> - 周五下午，精神科，挂号费 14.5 元。
> - 周二下午，六角亭心理咨询门诊
> 
> 精神科可开证，心理咨询门诊待探索。

2024-04-11 02:01 UTC, Hatsushigure commented
好

2024-04-11 02:10 UTC, Cryolitia requested changes

2024-04-11 02:10 UTC, Cryolitia commented on content/zh-cn/docs/psyco/hubei/li-fu/index.md
> +精神科**可开证**，心理咨询门诊*待探索*。
```suggestion
精神科**可开证**，心理咨询门诊**待探索**。
```

2024-04-11 03:13 UTC, Hatsushigure commented
我cpu干烧了，刚才发现李赋周三上午和周五上午在六角亭还有精神科门诊…算了，这个先不记录了，下周再看看是不是稳定排班

2024-04-11 06:16 UTC, Cryolitia approved these changes

2024-04-11 06:16 UTC, merged