通俗用语添加通往小证大证假条解释的超链接
project-trans/MtF-wiki pull request #1026
Opened 2024-05-24 06:40 UTC by ddzzkunye

通俗用语添加通往小证大证假条解释的超链接,方便查找.  
我当时怎么也找不到...

2024-05-25 12:18 UTC, LittleSound requested changes

2024-05-25 12:18 UTC, LittleSound commented on content/zh-cn/docs/useful-info/colloquialism.md
> +在[精神科医疗资源综述]({{<wiki "psyco-overview#collouialism">}})中的通俗用语一节有描述
链接存在问题，无法正常渲染和跳转。

```suggestion
在[精神科医疗资源综述]({{< ref "psyco-overview#colloquialism" >}})中的通俗用语一节有描述  
```

2024-05-26 02:12 UTC, BeiyanYunyi approved these changes

2024-05-26 03:40 UTC, LittleSound approved these changes

2024-05-26 04:24 UTC, merged