Upd:hrt/puth
project-trans/MtF-wiki pull request #1047
Opened 2024-07-08 10:04 UTC by Momoko-Ayase

补充了一点自己踩坑后的注意事项（本部和北方院区之间来回跑不好玩呜呜呜 改国疗超声合起来多出七百多花费不好玩呜呜呜）

2024-07-08 10:18 UTC, Catherina0 reviewed
198-201行是否应该更加书面化？

2024-07-08 10:36 UTC, Catherina0 requested changes
198-201建议修改

1. 约在诊前两周进行染色体检查（可选）。  
1. 初次就诊时，请在早晨前往医院，领取检查单后缴费，首先进行血液检查。  
1. 完成血液检查后，预约乳腺超声和骨密度检查。如当日预约已满，可预约复诊当天的号。  
1. 按照预约时间进行骨密度和乳腺检查，并现场领取检查结果。  
1. 复诊时，携带「易性症」病历，前往刘医生或潘医生处复查，如无问题，可当天获得处方及药物。

2024-07-08 13:08 UTC, Momoko-Ayase commented
> 198-201行是否应该更加书面化？

看了一下那部分还是老早之前#304 写的 我也就删了个“拿着「易性症」病历”（光开检查没用到）然后把前面那部分编号动了一下（不影响最终显示）

（其实是不是早上去做检查问题倒不大 只要能忍受饿一天（草

2024-07-08 14:29 UTC, AnnaBeiyan approved these changes
感谢您的贡献，如果您有空，可以参考相关建议进行修改，谢谢！

2024-07-08 14:29 UTC, AnnaBeiyan commented on content/zh-cn/docs/hrt/puth/_index.md
> +如果携带了「易性症」诊断的病历或证明，则医生会开具检查。（如果已经在在 3 个月内进行过其中部分检查，可以告知医生，以免重复进行；如果已经进行过全部检查，则可以直接将这次就诊视为「第二次就诊」，即制定 HRT 方案。）（检查申请单也可由其他内分泌科医生开具（本部和北方院区皆可，后者在当天也容易挂到号且也可开本部检查单），可免除为检查单独抢医生门诊号的麻烦）通过这些检查医生会确定你的身体情况是否适
这个是否考虑写在下面，和外院检查部分合并，因为考虑到请非跨性别门诊的医生开具相应检查是需要额外沟通成本的，并且下方的检查内容也未必是最新的。
建议的更改为
`北医三院承认外院检查结果。上述化验检查若在当地完善，建议在具有一定规模的三甲医院完成，一般内分泌科的医生会熟悉上述检查~~甚至知道你做这些是为了HRT~~，可请其照单开具。同样的，也可以找北医三院任何院区的任何内分泌科医生请其照单开具（本部和北方院区皆可，后者在当天也容易挂到号且也可开本部检查单）。`
修改位置在“第二次就诊”小标题的前面两行。这里的更改不要。

2024-07-08 14:29 UTC, AnnaBeiyan commented on content/zh-cn/docs/hrt/puth/_index.md
> +如果携带了「易性症」诊断的病历或证明，则医生会开具检查。（如果已经在在 3 个月内进行过其中部分检查，可以告知医生，以免重复进行；如果已经进行过全部检查，则可以直接将这次就诊视为「第二次就诊」，即制定 HRT 方案。）（检查申请单也可由其他内分泌科医生开具（本部和北方院区皆可，后者在当天也容易挂到号且也可开本部检查单），可免除为检查单独抢医生门诊号的麻烦）通过这些检查医生会确定你的身体情况是否适
```suggestion
如果携带了「易性症」诊断的病历或证明，则医生会开具检查。（如果已经在在 3 个月内进行过其中部分检查，可以告知医生，以免重复进行；如果已经进行过全部检查，则可以直接将这次就诊视为「第二次就诊」，即制定 HRT 方案。）通过这些检查医生会确定你的身体情况是否适合进行 HRT，并且会帮助监测一些副作用。（大部分人会有骨量减少，需要补充维生素 D．）涉及的检查包括：
```

2024-07-08 14:29 UTC, AnnaBeiyan commented on content/zh-cn/docs/hrt/puth/_index.md
> +
考虑到可能在北方院区做相关检查的跨女数量较少，倾向于不做如此明显的提示。因为已知跨性别门诊的医生是应该足够清楚相关问题的。同样建议补充到外院检查相关内容位置后面，不用加“warning”模板。

2024-07-08 14:29 UTC, AnnaBeiyan commented on content/zh-cn/docs/hrt/puth/_index.md
> +2. 初次就诊时，请在早晨前往医院，领取检查单后缴费，首先进行血液检查。
```suggestion
2. 初诊时，按预约时间前往医院，领取检查单后缴费，首先进行血液检查。
```

早上去不叫你号也没用吧，得看首诊预约时间

2024-07-08 15:44 UTC, sakuraanzu approved these changes

2024-07-09 16:37 UTC, Cryolitia requested changes

2024-07-09 16:37 UTC, Cryolitia commented on content/zh-cn/docs/hrt/puth/_index.md
> +{{< notice warning "注意" >}}
```suggestion
{{< notice info "开具性激素六项检查" >}}
```

2024-07-09 16:43 UTC, AnnaBeiyan commented on content/zh-cn/docs/hrt/puth/_index.md
> +{{< notice warning "注意" >}}
我提出的建议她好像看错了，我之前说让把激素这部分合并到外院检查里面，结果她把超声检查挪出去了。我还是建议这部分挪到外院检查部分，并且不用加这个warning模板。只有不在跨性别门诊就诊时才需要这个。

2024-07-10 04:00 UTC, AnnaBeiyan approved these changes

2024-07-12 04:17 UTC, Cryolitia approved these changes

2024-07-12 04:17 UTC, merged