translate(ja): readme
project-trans/MtF-wiki pull request #1050
Opened 2024-07-09 14:03 UTC by Felinya

Translation test, first time using github & markdown.

2024-07-09 16:32 UTC, Cryolitia commented
可能需要具有日语能力的审阅者帮忙审阅内容

2024-07-09 23:51 UTC, ishiharatsubaki commented
喵喵喵～？需要帮忙吗？

2024-07-10 00:13 UTC, Cryolitia commented
> 喵喵喵～？需要帮忙吗？

可以帮忙review一下（？

2024-07-10 01:55 UTC, Felinya commented
日语我倒是可以，不过能帮我审一下我格式写对了没吗
第一次写md+第一次用github（准备从这开始把hrt理论相关全翻掉

2024年7月10日(水) 9:13 PukNgae Cryolitia ***@***.***>:

> 喵喵喵～？需要帮忙吗？
>
> 可以帮忙review一下（？
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/project-trans/MtF-wiki/pull/1050#issuecomment-2219108240>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AR6TWJK2Q4RKBN6SESDI7ZLZLR4ENAVCNFSM6AAAAABKS6GLH2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEMJZGEYDQMRUGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-07-10 01:58 UTC, ishiharatsubaki commented
是这样的，我这边也是第一次用github，部分功能操作还需要再熟悉一下
不过专业能力没问题的

2024-07-10 06:20 UTC, Bersella-AI approved these changes
日本語ホームページをご改訂していただきありがとうございます！完璧な文筆です！今後、日本語への翻訳をご指導させていただけませんか？

Thank you for revising the Japanese homepage! What a fluent writing! Would you help us improve the writing quality in other Japanese pages?

2024-07-10 08:25 UTC, Felinya commented
Bersellaさんなど編集者さんたち

ありがとうございます。ちょうど日本語話者の人を集めて、中国語版のものを（医療関係の部分を重んじながら）日本語版に訳出してみようとしています。CryolitiaさんとWeblateなどの打ち合わせもしている最中ですが、関係者も多いということから、今はPRTSのディスコ鯖に入ってますがそこ（又は適切な他所）で打ち合わせしてもよろしいんですか？ディスコでもFelinyaという名前で既に入ってます。なお中国語でも構いません。

拝謝 Felinya

2024年7月10日(水) 15:20 水無月 心愛 ***@***.***>:

> ***@***.**** approved this pull request.
>
> 日本語ホームページをご改訂していただきありがとうございます！完璧な文筆です！今後、日本語への翻訳をご指導させていただけませんか？
>
> Thank you for revising the Japanese homepage! What a fluent writing! Would
> you help us improve the writing quality in other Japanese pages?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/project-trans/MtF-wiki/pull/1050#pullrequestreview-2168129743>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AR6TWJKQRM5QVDBFI7QXT7DZLTHCNAVCNFSM6AAAAABKS6GLH2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNRYGEZDSNZUGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-07-10 09:52 UTC, ishiharatsubaki commented
遅いところで申し訳ございません。
先程までずっと用事があるので今からきちんとレビューをしていきます。

2024-07-12 04:25 UTC, Cryolitia requested changes

2024-07-12 04:25 UTC, Cryolitia commented on README-JA.md
> +翻訳含め、ご投稿は <hi@mtf.wiki> より、GitHub が使える方は[公式レポジトリ](https://github.com/project-trans/MtF-wiki) での PR でも構いません。翻訳やお住まいの地域のトランスに関する情報のご提供を、楽しみにしております。 {{< /notice >}}
```suggestion
{{< notice info >}} 

本ウィキは当初、中国のトランスジェンダーの相互扶助と福祉のために設立されたものですが、後に日本用のページを開設したものですから、翻訳は全体的に未完成です（お許しください）。特に医療系の情報などについては、[中国版](README.md)からの翻訳が多数必要ですから、もしお手伝いがご希望な場合、心より感謝いたします。

翻訳含め、ご投稿は <hi@mtf.wiki> より、GitHub が使える方は[公式レポジトリ](https://github.com/project-trans/MtF-wiki) での PR でも構いません。翻訳やお住まいの地域のトランスに関する情報のご提供を、楽しみにしております。 

{{< /notice >}}
```

2024-07-17 07:18 UTC, shiawasenahikari commented
可以提一嘴吗，45 行这里

> 現在の MtF.wiki 日本語版は発展途上のものです。各種資料が未完成であったり、日本語が不十分であったり、誤りがある場合もあります。そのために、一人一人の貢献・ご投稿をいつも歓迎しております。

这里的「いつも」是不是应该换成「いつでも」，类比就是汉语里“总是”与“随时”的区别

2024-11-01 09:46 UTC, Cryolitia commented
> 可以提一嘴吗，45 行这里
> 
> > 現在の MtF.wiki 日本語版は発展途上のものです。各種資料が未完成であったり、日本語が不十分であったり、誤りがある場合もあります。そのために、一人一人の貢献・ご投稿をいつも歓迎しております。
> 
> 这里的「いつも」是不是应该换成「いつでも」，类比就是汉语里“总是”与“随时”的区别

不过这位好像是真太君来着（小声

2024-11-01 20:34 UTC, saeziae commented
merge conflit needs to be resolved, looking into it later.

2024-11-03 09:12 UTC, merged