增加浦东新区人民医院
project-trans/MtF-wiki pull request #1068
Opened 2024-07-25 09:41 UTC by AnnaBeiyan

close #1053

2024-07-26 03:02 UTC, Cryolitia requested changes
对于缺乏详细报告的建议加在 https://github.com/project-trans/MtF-wiki/blob/master/content/zh-cn/docs/hrt/shanghai/_index.md

2024-07-29 16:46 UTC, btogxx requested changes

2024-07-29 16:46 UTC, btogxx commented on content/zh-cn/docs/hrt/shanghai/_index.md
> +浦东新区人民医院,,王颖,凭诊断证明可开手工处方单
内分泌科 专家号

2024-07-31 18:08 UTC, wxjstz approved these changes

2024-07-31 18:15 UTC, btogxx approved these changes

2024-07-31 18:17 UTC, merged