add：部分产品在常见原产地的上市信息
project-trans/MtF-wiki pull request #1102
Opened 2024-08-30 05:08 UTC by LeeGuanLi

增添部分产品在常见原产地的上市信息，修改部分过时信息（国补上市批文）
增添常见原产地的上市信息有助于帮助部分商家整理对自己的有利信息，维护自己的合法权益。

2024-08-30 07:31 UTC, Cryolitia commented
感谢贡献，该PR可能需要等待我们的药物组编辑审阅，若等候时间过长提前在此致歉。

2024-08-30 16:06 UTC, Bersella-AI requested changes
非常感谢，已就诸批准文号进行查询验证，结果为：

- “土色”方面，因土耳其官方监管机构的网站（<https://turkfarmakopesi.titck.gov.tr/>）无法经广电网络或其它信道访问，故暂无法验证。
- 新西兰 Siterone 方面确认属实[^1] [^2]。
- “泰补”方面确认属实。
- 泰国凝胶方面确认属实[^3]。

其实目前为止这里仅记录大中华区上市状态，主要是出于本站受众主要来自大中华区的缘故；其次，收集大中华区以外的上市状况，会大大增加本人的无谓负担（对，药物板块的常驻编辑只有我😂），毕竟为了证据严谨，我必然要四处搜集、整理文献并从中提取有用的信息，这老费精力了……总之如果可以的话，有几件小事拜托一下。

1. 于以下标记处增补官方监管机构的药品数据库/批准信息链接。
2. 为 Androcur 增补在原产地：德国的批准文号。
3. 为“泰补”增加 2 mg 剂型的批准文号。

[^1]: https://www.medsafe.govt.nz/Regulatory/ProductDetail.asp?ID=9839
[^2]: https://www.medsafe.govt.nz/Regulatory/ProductDetail.asp?ID=11168
[^3]: https://pertento.fda.moph.go.th/FDA_INFORMATION_DRUG/Home/Phar_Product_Inform_Page?Newcode=U1DR1C1022640000111C

2024-08-30 16:06 UTC, Bersella-AI commented on content/zh-cn/docs/medicine/antiandrogen/cyproterone/index.md
> +- 上市信息：11168, 9839
建议为此增加到新西兰官方监管机构数据库（medsafe.govt.nz）的链接。

2024-08-30 16:06 UTC, Bersella-AI commented on content/zh-cn/docs/medicine/antiandrogen/cyproterone/index.md
> +土耳其,8699546011667
同样地，建议增补来源链接。因网络原因，本人无从验证，可能需要第三方辅助确认。

2024-08-30 16:06 UTC, Bersella-AI commented on content/zh-cn/docs/medicine/estrogen/gel/index.md
> +| 泰国 | U1DR1C1022640000111C |
同上，建议增补官方监管机构的批准信息链接。

2024-08-31 03:56 UTC, LeeGuanLi commented on content/zh-cn/docs/medicine/antiandrogen/cyproterone/index.md
> +土耳其,8699546011667
土色官网仅能查询药品名录，无法查询批准文号。可通过https://www.rxreasoner.com/drugs/androcur查询相关信息，稍晚些将会提交新pr

2024-08-31 04:02 UTC, LeeGuanLi commented on content/zh-cn/docs/medicine/antiandrogen/cyproterone/index.md
> +- 上市信息：11168, 9839
新西兰同上，官方网站只能查，不显示具体详细信息，需依靠第三方网站
新西兰官方机构：https://www.medsafe.govt.nz/Medicines/SearchResult.asp
而且拿asp做的网页也没办法提供可以直接跳转到目的地的直链））

2024-08-31 04:47 UTC, LeeGuanLi commented
@Bersella-AI 
1.新增了cpa板块的批准信息链接和德色的批准文号
2.泰补批文本身就是2mg规格，无需更正
3.凝胶批文的超链接已添加
4.诺的信息已补充



ps：如果缺人，希望可以加入你们。自荐信已于昨天发送至hi@project-trans.org，发件人：lee@mtftm.com
对此方面我有充分的优势和经验，同时拥有大量时间。

2024-08-31 06:01 UTC, Cryolitia commented
@LeeGuanLi 未收到相关邮件，请发送到 admin@project-trans.org 同时抄送 Cryolitia@gmail.com

2024-08-31 06:15 UTC, LeeGuanLi commented
> @LeeGuanLi 未收到相关邮件，请发送到 [admin@project-trans.org](mailto:admin@project-trans.org) 同时抄送 [Cryolitia@gmail.com](mailto:Cryolitia@gmail.com)

已发送，原收件地址为 "Project Trans" GitHub组织首页留存的邮箱~ 如有变动，建议修改
<img width="631" alt="image" src="https://github.com/user-attachments/assets/29be0975-2ea7-4f07-9eae-03bb4716371f">

2024-08-31 06:16 UTC, Cryolitia commented
@LeeGuanLi hi@project-trans.org 无法收到邮件的问题为非预期的内部错误，正在排查

CC @saeziae

2024-08-31 08:51 UTC, Bersella-AI requested changes
提请注意：第三方资料来源不能代替官方监管机构或平台的第一方资讯，应进行详尽的 fact check，详情见下。

2024-08-31 08:51 UTC, Bersella-AI commented on content/zh-cn/docs/medicine/antiandrogen/cyproterone/index.md
> +- [上市信息：02579062](https://www.rote-liste.de/suche/praep/7189-0/Androcur%C2%AE%2010%C2%A0mg%20Tabletten)
应以德国官方监管机构数据库（<https://auth.bfarm.de/sso-home/amguifree>）的记录为准。在该处搜索商品名 Androcur，可见 10 条结果，批准文号分别为：

- 66098.00.00（Kohlpharma GmbH）
- 66254.00.00
- 67321.00.00
- 25926.00.00（10 mg,Kohlpharma GmbH）
- 29667.00.00
- 7013484.00.00
- 2956.00.00（Jenapharm GmbH）
- 43162.00.00
- 85605.00.00
- 2204156.00.00

2024-08-31 08:51 UTC, Bersella-AI commented on content/zh-cn/docs/medicine/antiandrogen/cyproterone/index.md
> +- 上市信息：[11168, 9839](https://www.rxreasoner.com/drugs/siterone)
同样地，以新西兰官方监管机构数据库（www.medsafe.govt.nz）的资料和链接为准。链接可见本人昨晚的回复。

2024-08-31 08:51 UTC, Bersella-AI commented on content/zh-cn/docs/medicine/antiandrogen/cyproterone/index.md
> +| 土耳其   | [8699546011667](https://www.rxreasoner.com/drugs/androcur)   |
此号码经查询为国际通用 GS1 商品码，注册者为拜耳土耳其分公司，查询结果来自：<http://www.gs1cn.org/search/external>。**商品码不等于当地药品监管机构的批准文号**，提请留意。

2024-08-31 09:10 UTC, LeeGuanLi commented on content/zh-cn/docs/medicine/antiandrogen/cyproterone/index.md
> +- [上市信息：02579062](https://www.rote-liste.de/suche/praep/7189-0/Androcur%C2%AE%2010%C2%A0mg%20Tabletten)
德色已更正，由于种类繁多，故只取了wiki样图上的版本。

2024-08-31 09:17 UTC, LeeGuanLi commented on content/zh-cn/docs/medicine/antiandrogen/cyproterone/index.md
> +- 上市信息：[11168, 9839](https://www.rxreasoner.com/drugs/siterone)
1.新西兰官方数据库无法导出针对某一药品的链接，将通过插入pdf解决。
2.新西兰官方数据库不显示批准文号，已移除。

2024-08-31 09:34 UTC, LeeGuanLi commented on content/zh-cn/docs/medicine/antiandrogen/cyproterone/index.md
> +| 土耳其   | [8699546011667](https://www.rxreasoner.com/drugs/androcur)   |
土耳其官方平台不直接显示批准文号，批准文号藏在kub文件第15页里。。
这个我就直接放kub文件的链接了

2024-08-31 09:35 UTC, Bersella-AI commented
我帮个小忙罢😊 这是我手上的土耳其 Androcur （“土色”）包装，下面一行字 Ruhsat numarası 意为“许可证号”，应该可以视为在土耳其有效的批准文号。

![IMG20240831173109](https://github.com/user-attachments/assets/35b96818-4182-464d-89b9-62e584279831)

2024-08-31 09:35 UTC, LeeGuanLi commented on content/zh-cn/docs/medicine/antiandrogen/cyproterone/index.md
> +| 土耳其   | [8699546011667](https://www.rxreasoner.com/drugs/androcur)   |
8. RUHSAT NUMARASI 
88/77

2024-08-31 09:38 UTC, LeeGuanLi commented
> 我帮个小忙罢 😊 这是我手上的土耳其 Androcur （“土色”）包装，下面一行字 Ruhsat numarası 意为“许可证号”，应该可以视为在土耳其有效的批准文号。
> 
> ![IMG20240831173109](https://private-user-images.githubusercontent.com/17742380/363403203-35b96818-4182-464d-89b9-62e584279831.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwOTczNTgsIm5iZiI6MTcyNTA5NzA1OCwicGF0aCI6Ii8xNzc0MjM4MC8zNjM0MDMyMDMtMzViOTY4MTgtNDE4Mi00NjRkLTg5YjktNjJlNTg0Mjc5ODMxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDA5MzczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MWRiNmZkNzc1NjZkNjRjYTg3MGJlOGE1YTI0NDdiMDQwNWJhNzY5ZTEzNjQ4OWFhZDg1NDc5YzdjZTJjNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sK7m0myYyLe5cPsPgl9K_vQA7Rz7a04Gr8pFpPiBj5M)

草）我才从kub文件里扣出来.jpg
不过这下侧面印证了我没找错

2024-08-31 09:42 UTC, LeeGuanLi commented
更新汇总：
1.更正了土色的批准文号和引用链接（kub文件）
2.更正了德色相关信息
3.移除了新色的批准文号，增加了新色的批准文件。

2024-08-31 09:50 UTC, Bersella-AI requested changes
做得很棒，有一点我需要补充一下。

2024-08-31 09:50 UTC, Bersella-AI commented on content/zh-cn/docs/medicine/antiandrogen/cyproterone/index.md
> +[^1]: Wikipedia. Chlormadinone acetate [EB/OL]. [2023-11-25](2024-05-01). <https://en.wikipedia.org/wiki/Chlormadinone_acetate>
这个格式是有意为之。不妨参照国家标准 GB/T 7714-2005，其中电子文档的引用规范中，小括号为发布/修订日期，中括号为最近一次浏览日期。

2024-08-31 09:55 UTC, LeeGuanLi commented on content/zh-cn/docs/medicine/antiandrogen/cyproterone/index.md
> +[^1]: Wikipedia. Chlormadinone acetate [EB/OL]. [2023-11-25](2024-05-01). <https://en.wikipedia.org/wiki/Chlormadinone_acetate>
怪，印象中没动过这里（）
可能是编辑器干的（划掉

2024-08-31 10:01 UTC, LeeGuanLi commented on content/zh-cn/docs/medicine/antiandrogen/cyproterone/index.md
> +[^1]: Wikipedia. Chlormadinone acetate [EB/OL]. [2023-11-25](2024-05-01). <https://en.wikipedia.org/wiki/Chlormadinone_acetate>
崩，测试后发现确实是vs code干的
它觉得这是错的，于是在保存的一瞬间更改了内容
我找找这功能在哪关）

2024-08-31 10:25 UTC, Bersella-AI approved these changes
好！做药物信息重在证据链严丝合缝，你成功地迈出了第一步，再接再厉！ :+1:

2024-08-31 12:18 UTC, saeziae commented
> @LeeGuanLi hi@project-trans.org 无法收到邮件的问题为非预期的内部错误，正在排查
> 
> CC @saeziae

the address for mtfwiki is mtfwiki@project-trans.org or hi@mtf.wiki

2024-08-31 13:09 UTC, LeeGuanLi commented
> > [hi@project-trans.org](mailto:hi@project-trans.org) 无法收到邮件的问题为非预期的内部错误，正在排查
> > 抄送
> 
> MTFwiki 的地址是 [mtfwiki@project-trans.org](mailto:mtfwiki@project-trans.org) 或 [hi@mtf.wiki](mailto:hi@mtf.wiki)

@saeziae 这个邮箱是GitHub页面内预留的，建议更正一下）
https://github.com/project-trans
![image](https://github.com/user-attachments/assets/545776be-a6b9-411a-9267-ae339dd7b2d5)

2024-08-31 13:24 UTC, saeziae commented
> @saeziae 这个邮箱是GitHub页面内预留的，建议更正一下）

Thanks. It has been updated to an existing address.

2024-09-01 02:55 UTC, Cryolitia approved these changes

2024-09-01 02:55 UTC, merged