添加张霞
project-trans/MtF-wiki pull request #1136
Opened 2024-09-29 19:29 UTC by Oriyukiiii

2024-09-29 19:32 UTC, Leetfs approved these changes

2024-09-30 01:49 UTC, AnnaBeiyan requested changes

2024-09-30 01:49 UTC, AnnaBeiyan commented on content/zh-cn/docs/hrt/liaoning/_index.md
> +```
已经有独立页面的内容不需要再这里重复写。
```suggestion

```

2024-09-30 01:49 UTC, AnnaBeiyan commented on content/zh-cn/docs/hrt/liaoning/zhang-xia/index.md
> +- 需要 大连七院的易性症 证明。
确定只认可大连七院的证明吗

2024-09-30 01:57 UTC, Leetfs commented
@AnnaBeiyan 据本地经常全国巡游刷证的某人反馈是这样的，但截止到发稿日的最新情况未知。

2024-09-30 01:58 UTC, AnnaBeiyan approved these changes

2024-09-30 01:59 UTC, merged