docs: Update Resource Lists for Voice Therapy and FFS in US
project-trans/MtF-wiki pull request #1161
Opened 2024-10-11 17:02 UTC by ZL-Asica

1. **Facial Feminization Surgery (FFS)**:
   - 添加 NM 的 3 位 FFS 医生（保险信息及联系方式）

2. **Voice Therapy**:
   - 添加 UCI Health 的 1 位医生（保险疗程及 CPT code）
   - 添加 NM 的 3 位医生（预约电话及流程）

2024-10-11 22:53 UTC, Leetfs requested changes

2024-10-11 22:53 UTC, Leetfs commented on content/zh-cn/docs/vocal-therapy/vocal-therapy-confirmed.md
> +美国,Northwestern Medicine,Jonelyn Langenstein (Chicago DT) <br> Sarah Penzell <br> Nathan Waller (Evanston),"预约电话：[312-695-8182](tel:312-695-8182) (Chicago DT) <br> [847-491-3165](tel:847-491-3165) (E
```suggestion
美国,UCI Health Speech Therapy,Jennifer Kim,一个疗程10节课,CPT® code 92507。
美国,Northwestern Medicine,Jonelyn Langenstein (Chicago DT) <br> Sarah Penzell <br> Nathan Waller (Evanston),"预约电话：[312-695-8182](tel:312-695-8182) (Chicago DT) <br> [847-491-3165](tel:847-491-3165) (Evanston)",打电话时请 request to schedule with an ENT，以便后续保险报销。
```

2024-10-11 22:54 UTC, ZL-Asica commented on content/zh-cn/docs/vocal-therapy/vocal-therapy-confirmed.md
> +美国,Northwestern Medicine,Jonelyn Langenstein (Chicago DT) <br> Sarah Penzell <br> Nathan Waller (Evanston),"预约电话：[312-695-8182](tel:312-695-8182) (Chicago DT) <br> [847-491-3165](tel:847-491-3165) (E
感谢感谢

2024-10-11 23:03 UTC, Leetfs approved these changes

2024-10-12 03:54 UTC, AnnaBeiyan commented on content/zh-cn/docs/vocal-therapy/vocal-therapy-confirmed.md
> +美国,Northwestern Medicine,Jonelyn Langenstein (Chicago DT) <br> Sarah Penzell <br> Nathan Waller (Evanston),"预约电话：[312-695-8182](tel:312-695-8182) (Chicago DT) <br> [847-491-3165](tel:847-491-3165) (E
为啥这块要换成英文逗号啊。如果要换英文逗号逗号后面应该加空格吧

2024-10-12 03:57 UTC, Leetfs commented on content/zh-cn/docs/vocal-therapy/vocal-therapy-confirmed.md
> +美国,Northwestern Medicine,Jonelyn Langenstein (Chicago DT) <br> Sarah Penzell <br> Nathan Waller (Evanston),"预约电话：[312-695-8182](tel:312-695-8182) (Chicago DT) <br> [847-491-3165](tel:847-491-3165) (E
> 为啥这块要换成英文逗号啊。如果要换英文逗号逗号后面应该加空格吧

因为这里的 ` , ` 是用来划分csv格子的。每一行的字段数量需要一致，否则无法构建

2024-10-12 03:58 UTC, ZL-Asica commented on content/zh-cn/docs/vocal-therapy/vocal-therapy-confirmed.md
> +美国,Northwestern Medicine,Jonelyn Langenstein (Chicago DT) <br> Sarah Penzell <br> Nathan Waller (Evanston),"预约电话：[312-695-8182](tel:312-695-8182) (Chicago DT) <br> [847-491-3165](tel:847-491-3165) (E
对的是用来切分csv的，这里是我的问题。

2024-10-12 03:58 UTC, AnnaBeiyan commented on content/zh-cn/docs/vocal-therapy/vocal-therapy-confirmed.md
> +美国,Northwestern Medicine,Jonelyn Langenstein (Chicago DT) <br> Sarah Penzell <br> Nathan Waller (Evanston),"预约电话：[312-695-8182](tel:312-695-8182) (Chicago DT) <br> [847-491-3165](tel:847-491-3165) (E
抱歉，手机上没仔细看

2024-10-12 03:59 UTC, AnnaBeiyan approved these changes

2024-10-12 03:59 UTC, merged