修改北医三院医生出诊细节和注意事项
project-trans/MtF-wiki pull request #1164
Opened 2024-10-14 04:32 UTC by Hsuanching318

2024-10-14 05:02 UTC, AnnaBeiyan requested changes

2024-10-14 05:02 UTC, AnnaBeiyan commented on content/zh-cn/docs/hrt/puth/_index.md
> +开始 HRT 之后要求每三个月复查一次，以继续开具药物。要求的检查项目包括：肝肾功能、血脂、血糖、电解质（以上项目可以直接和医生说检查生化组合）、性激素（睾酮、雌二醇、泌乳素，这三项为必查的三项，查六项也没关系），视情况可能会有其他检查项目。
确定血常规和二聚体所有医生都不将其作为复查项目了吗？我看本来模样的公众号还说有。

2024-10-14 05:02 UTC, AnnaBeiyan commented on content/zh-cn/docs/hrt/puth/pan-bailin/index.md
> +1.  北医三院药房目前并无醋酸环丙孕酮。如有需要可请医生在处方上手写加注，自行院外购买；或于好大夫在线[线上问诊]({{< ref "puth#线上问诊" >}})并购买。
```suggestion
1. 北医三院药房目前并无醋酸环丙孕酮。如有需要可请医生在处方上手写加注，自行院外购买；或于好大夫在线[线上问诊]({{< ref "puth#线上问诊" >}})并购买。
```

2024-10-14 05:02 UTC, AnnaBeiyan commented on content/zh-cn/docs/hrt/puth/pan-bailin/index.md
> +2.  北医三院药房有爱斯妥，目前可开出。
```suggestion
2. 北医三院药房有爱斯妥，目前可开出。
```

2024-10-14 19:52 UTC, Hsuanching318 commented on content/zh-cn/docs/hrt/puth/_index.md
> +刘烨,周二晚间,内科-内分泌科晚间门诊(特需),健康医学楼七层
> 
系统里写着在六楼，其实在七楼（至少上个月是这样的

2024-10-14 19:56 UTC, Hsuanching318 commented on content/zh-cn/docs/hrt/puth/_index.md
> +开始 HRT 之后要求每三个月复查一次，以继续开具药物。要求的检查项目包括：肝肾功能、血脂、血糖、电解质（以上项目可以直接和医生说检查生化组合）、性激素（睾酮、雌二醇、泌乳素，这三项为必查的三项，查六项也没关系），视情况可能会有其他检查项目。
> 确定血常规和二聚体所有医生都不将其作为复查项目了吗？我看本来模样的公众号还说有。

最近半年我自己和我参与登记的在三院做的都没有这两项

2024-10-14 23:37 UTC, AnnaBeiyan commented on .gitignore
> +.Rproj.user
不好意思这里没说清楚，意思是不要这个新增的这一行，不是不要这个文件。把这个文件按原来内容恢复我这里就没问题了。

```
public/
resources/

*.DS_Store

.hugo_build.lock

.idea

node_modules
```

2024-10-15 08:19 UTC, AnnaBeiyan approved these changes

2024-10-15 08:23 UTC, Leetfs approved these changes

2024-10-15 08:24 UTC, merged

2025-03-09 08:53 UTC, Cryolitia commented
您好，请问一下骨密度可以使用超声法的来源是什么，此前潘柏林曾经特别提醒过必须使用双能X射线法

2025-03-13 19:28 UTC, Hsuanching318 commented
因为我当时在三院当助理的时候两种方法测的骨密度我们都接受并且录入的，而且潘医生其实也没说什么

2025-03-13 20:39 UTC, Cryolitia commented
> 因为我当时在三院当助理的时候两种方法测的骨密度我们都接受并且录入的，而且潘医生其实也没说什么

这边社群里最近又有人提出了对这一点的异议，我个人印象中是有过必须双能X射线法的要求的。翻了半天资料库只找到一个邮件，所以暂时先回退一下这一点的更改。如果可能的话也辛苦您和潘/刘老师再确认一下更为妥当。

![image](https://github.com/user-attachments/assets/b69697fc-598f-4d43-9c3e-7e49278ae2e1)

2025-04-07 21:54 UTC, Hsuanching318 commented
我去问了一下，回复是这样的：一般（原则上）是要求用DXA，但是有时候一些未成年的去医院可能会出现没有对应数据的情况，这时候可能会拿超声测桡骨密度来近似一下