docs(hrt): add 山东大学齐鲁医院（青岛）｜何兰杰
project-trans/MtF-wiki pull request #1192
Opened 2024-10-31 01:51 UTC by Leetfs

close #1191

2024-10-31 02:32 UTC, Cryolitia requested changes
1. 单个页面没有必要建立二级菜单
2. 提升警告级别
3. 强关联的同一个医院需要交叉引用

我正在改

2024-10-31 02:33 UTC, Lodolala commented
怕医生被爆破...？
我感觉注意事项里自购的那一句话可以改成「医生可能会根据医院实际情况只给予用药指导」

2024-10-31 02:44 UTC, Cryolitia approved these changes

2024-11-03 09:37 UTC, saeziae approved these changes

2024-11-03 09:37 UTC, merged