更新高绿芬诊室具体地址
project-trans/MtF-wiki pull request #1273
Opened 2024-12-31 01:50 UTC by dongguacute

2024-12-31 03:23 UTC, BeiyanYunyi requested changes

2024-12-31 03:23 UTC, BeiyanYunyi commented on content/zh-cn/docs/hrt/jnuh1/index.md
> +就诊地址：暨南大學附属第一医院2号楼5楼（即一号楼与三号楼通道的右侧），跨性别序列门诊与妇科门诊是就诊诊室相同
```suggestion
就诊地址：暨南大学附属第一医院 2 号楼 5 楼（即一号楼与三号楼通道的右侧），跨性别序列门诊与妇科门诊诊室相同。
```

2024-12-31 03:55 UTC, BeiyanYunyi requested changes

2024-12-31 03:55 UTC, BeiyanYunyi commented on content/zh-cn/docs/hrt/jnuh1/index.md
> +当天找医生看报告可以请分诊台护士再次排队
```suggestion
当天找医生看报告可以请分诊台护士再次排队。
```

2024-12-31 05:18 UTC, BeiyanYunyi approved these changes

2025-01-02 09:23 UTC, Cryolitia approved these changes

2025-01-02 09:23 UTC, merged