重写SERMs部分
project-trans/MtF-wiki pull request #827
Opened 2023-07-21 13:35 UTC by wmtdru8xip

原SERMs章节缺乏必要的信息，且建议的用药方案显然不适当。

2023-07-22 04:04 UTC, Bersella-AI requested changes
非常感谢你的投稿！我一直以来都没敢涉足SERM，一方面对这类药品的认识严重缺乏，另一方面对SERM的需求非常少，我以为没人会看的。这次 PR 给了我提醒，要爱屋及乌。  
这份重写的文章相当翔实，但是，仍有一系列论据上的缺陷：

1. **新文章未引用任何新的文献或资料来源。** 这会造成全文系编者主观臆断，而非客观事实而来的印象。
2. SERM 并非用于抗雄激素治疗，故无需提及抗雄激素相关事项。
3. 诸如 SHBG、IGF-1 等专业、非相关术语缩写，应予以解释。
4. 尚未发现证据表明雷洛昔芬是唯一适用于非二元性别肯定治疗的 SERM。如果雷洛昔芬在这方面较其它 SERM 有比较优势，应予以解释并引用相关文献；为何他莫昔芬不推荐使用，也应予以解释。从[现有文献](https://www.fertstert.org/article/S0015-0282(08)01280-6/fulltext)看，他莫昔芬会引起睾酮升高，而雷洛昔芬引起些微的睾酮升高。
5. 《SERM 对各组织的作用》显然是引自[维基百科的一张表格](https://en.wikipedia.org/wiki/Template:Tissue-specific_estrogenic_and_antiestrogenic_activity_of_SERMs)，应予以引用并注明。另外，可以考虑引用 PubMed 的[这份文献](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8253879/)的「表一」，其中对比了雌二醇和三种 SERM 的作用强度。
6. “120 mg/天的雷洛昔芬可使生物可利用睾酮（游离睾酮）水平增加 20%”的说法未引用任何文献佐证。据[已有文献](https://doi.org/10.1530/eje.0.1500539)，雷洛昔芬使游离睾酮增加约 13%，且有统计意义。
7. 为便于阅读，汉字和英语单词、数字之间应隔一个空格。

本人和 yucandy 已翻译《[对非二元女性倾向跨性别者的激素治疗可能性的探索](https://tfsci.mtf.wiki/articles/nonbinary-transfem-overview/)》，其中提及了 SERM，亦可酌情引用。

2023-07-22 04:30 UTC, wmtdru8xip commented
感谢你的审读！

> 新文章未引用任何新的文献或资料来源。 这会造成全文系编者主观臆断，而非客观事实而来的印象。

昨天晚上由于时间太迟，我未能加入文献引用。接下来的时间中我会尽量抽出时间完善。
> SERM 并非用于抗雄激素治疗，故无需提及抗雄激素相关事项。

由于使用SERMs时常用的抗雄激素疗法不适用，因此个人觉得有必要额外提及此条件下有效的抗雄激素疗法。
> 诸如 SHBG、IGF-1 等专业、非相关术语缩写，应予以解释。

好的，谢谢提醒。
> 如果雷洛昔芬在这方面较其它 SERM 有比较优势，应予以解释并引用相关文献；为何他莫昔芬不推荐使用，也应予以解释。

我将加入我所查阅的文献、专著和我的考虑。
>《SERM 对各组织的作用》显然是引自维基百科的一张表格，应予以引用并注明。

好的，谢谢提醒。
> “120 mg/天的雷洛昔芬可使生物可利用睾酮（游离睾酮）水平增加 20%”的说法未引用任何文献佐证。据已有文献，雷洛昔芬使游离睾酮增加约 13%，且有统计意义。

我看到的一篇文献好像显示为20（和原页面中所说的总睾酮增加量恰巧一样），不过我刚才又查询了一下，发现那篇文献的abstract里写的和正文里的不一样，我想那篇文献可能有质量问题。此外，感谢你的检查。

2023-07-22 04:46 UTC, Bersella-AI commented
> 我看到的一篇文献好像显示为20（和原页面中所说的总睾酮增加量恰巧一样），不过我刚才又查询了一下，发现那篇文献的abstract里写的和正文里的不一样，我想那篇文献可能有质量问题。此外，感谢你的检查。

嗯对，我们看的应该是同一篇，雷洛昔芬剂量正好是 120 mg/天，摘要中总睾酮、游离睾酮、生物可利用睾酮分别升高 20%、16% 和 20%。但从表格实际数据看，平均值的增幅是小于摘要所述增幅的，故先前得出“游离睾酮 +13%”的结论。对此，引述时除变幅以外，还应阐明睾酮绝对值的变化。

2023-07-24 11:39 UTC, wmtdru8xip commented
@Bersella-AI 我的修改尚未完成，但是劳烦检查一下当前的改动，并请告诉我是否有不妥之处，十分感谢！

2023-07-25 04:41 UTC, Bersella-AI reviewed
这个问题依然未得到解决：ERα 是什么？GPER 又是什么？在文首“简介”中不能略去其全称。

其次是有关排版的事项：

- 汉字和英语单词或缩写、数字之间，要留一空格，以改善阅读体验。
- 就图片的引用而言，Hugo 提供了以下格式：

```markdown
| 标题 1 | 标题 2 |
|:--:|:--:|
| ![图一](...) | ![图二](...) |
```

不过我本人忽视了一点，就是非二元性别肯定治疗当中不仅要**抗雄激素作用**，而且要尽量减少雌激素或雌激素作用的影响。抗雄制剂 + 雌激素的配方属于常规 GAHT，抗雄只是目标之一；对于非二元 GAHT 治疗，在部分促进女性化的情况下，要以 SERM 取代雌激素。故此，“一般疗法不适用”不应是“非二元治疗中抗雄制剂单药抑制睾酮不充分”的结果，二者没有因果关系；“一般疗法不适用”是因为需 SERM 介入的场合本就**不属于**常规 GAHT 的范畴。

其他部分做得很好，符合严谨论证的预期。:+1:

2023-08-12 14:40 UTC, Bersella-AI commented
刚刚翻译好了 FDA 批准的盐酸雷洛昔芬（Evista）说明书，其中罗列了具体副作用和风险。同时，说明书明确写道，雷洛昔芬**不能治疗浸润性乳腺癌，只能预防**；也即对于已经煮成熟饭的情况，其作用将微乎其微。故此，有必要提醒，雷洛昔芬对长期经常规激素治疗后的结果***不具备停滞或扭转作用***；只有在乳房尚未开始发育之时，雷洛昔芬方可具备延后发育的作用。

说明书译文可于此查阅，供参考：<https://tfsci.mtf.wiki/zh-cn/misc/evista/>

2023-08-13 11:06 UTC, wmtdru8xip commented
之前几日我由于一些原因较繁忙，未能完成编辑，在此致以歉意。刚才我又进行了一些改动。文章仍未全部完成，但是基本已达到可合并的条件。请再进行一次检查，十分感谢。

2023-08-13 11:17 UTC, septs commented on content/zh-cn/docs/medicine/SERMs/_index.md
> +| 托瑞米芬   | -    | +      | +      | +    | +    | +     | +        | -        | -    | O          |
````suggestion
```csv
组织,乳房,骨骼,,肝脏,,,子宫,阴道,脑,
作用,乳腺,骨密度,脂代谢,凝血,SHBG,IGF-1,子宫内膜,阴道干燥,潮热,促性腺激素
雌二醇,+,+,+,+,+,+,+,+,+,+
“理想 SERM”,-,+,+,O,O,O,-,+,+,O
巴多昔芬,-,+,+,+,+,?,-,O,-,?
氯米芬,-,+,+,?,+,+,-,?,-,O
拉索昔芬,-,+,+,+,?,?,O,O,-,?
奥培米芬,-,+,+,+,+,+,O,O,-,O
雷洛昔芬,-,+,+,+,+,+,O,-,-,O
他莫昔芬,-,+,+,+,+,+,+,-,-,O
托瑞米芬,-,+,+,+,+,+,+,-,-,O
```
````

2023-08-13 11:18 UTC, septs commented on content/zh-cn/docs/medicine/SERMs/_index.md
> +[^2]: 见维基百科相应条目
应更换为具体的链接

2023-08-13 11:20 UTC, septs commented on content/zh-cn/docs/medicine/SERMs/raloxifene/index.md
> +说明书：[见 tfsci.mtf.wiki](https://tfsci.mtf.wiki/zh-cn/misc/evista/)（感谢 Bersella-AI 于本文写作期间的翻译）
```suggestion
说明书：<https://tfsci.mtf.wiki/zh-cn/misc/evista/>
```

2023-08-13 11:21 UTC, septs commented on content/zh-cn/docs/medicine/SERMs/raloxifene/index.md
> +雷洛昔芬（Raloxifene）是一种常用的 SERM。作为一种 ERα 的部分激动剂、ERβ 的完全拮抗剂和 GPER（G 蛋白偶联雌激素受体）的激动剂，其在肝脏代谢、皮肤、骨骼、脂肪分布等方面起雌激素作用，在乳房发育、阴道干燥、潮热等方面起抗雌激素作用，无抗促性腺激素作用。在顺性别女性中，雷洛昔芬主要用于绝经后骨质疏松和乳腺癌的预防。[^4]在跨性别者中，其可以在带来女性化效果的同时抑制乳房
```suggestion
雷洛昔芬（Raloxifene）是一种常用的 SERM。作为一种 ER&alpha; 的部分激动剂、ER&beta; 的完全拮抗剂和 GPER（G 蛋白偶联雌激素受体）的激动剂，其在肝脏代谢、皮肤、骨骼、脂肪分布等方面起雌激素作用，在乳房发育、阴道干燥、潮热等方面起抗雌激素作用，无抗促性腺激素作用。在顺性别女性中，雷洛昔芬主要用于绝经后骨质疏松和乳腺癌的预防。[^4]在跨性别者中，其可以在带来女性化效果的同时抑制乳房发育[^3]。
```

2023-08-13 11:23 UTC, septs commented on content/zh-cn/docs/medicine/SERMs/raloxifene/index.md
> +雷洛昔芬（Raloxifene）是一种常用的 SERM。作为一种 ERα 的部分激动剂、ERβ 的完全拮抗剂和 GPER（G 蛋白偶联雌激素受体）的激动剂，其在肝脏代谢、皮肤、骨骼、脂肪分布等方面起雌激素作用，在乳房发育、阴道干燥、潮热等方面起抗雌激素作用，无抗促性腺激素作用。在顺性别女性中，雷洛昔芬主要用于绝经后骨质疏松和乳腺癌的预防。[^4]在跨性别者中，其可以在带来女性化效果的同时抑制乳房
refer https://symbl.cc/en/html-entities/

2023-08-13 11:28 UTC, wmtdru8xip commented on content/zh-cn/docs/medicine/SERMs/_index.md
> +[^2]: 见维基百科相应条目
请问指什么链接？

2023-08-13 11:30 UTC, wmtdru8xip commented on content/zh-cn/docs/medicine/SERMs/_index.md
> +| 托瑞米芬   | -    | +      | +      | +    | +    | +     | +        | -        | -    | O          |
个人反对这一改变：由于以后仍会改动此表，且原格式更适合在编辑器中被查看和修改。

2023-08-13 12:36 UTC, septs commented on content/zh-cn/docs/medicine/SERMs/_index.md
> +| 托瑞米芬   | -    | +      | +      | +    | +    | +     | +        | -        | -    | O          |
使用 CSV 格式是为了更好的维护 table

2023-08-13 12:37 UTC, septs commented on content/zh-cn/docs/medicine/SERMs/_index.md
> +[^2]: 见维基百科相应条目
```suggestion
[^2]: [拉索昔芬](https://en.wikipedia.org/wiki/Lasofoxifene)（英文）
```

2023-08-13 12:44 UTC, wmtdru8xip commented on content/zh-cn/docs/medicine/SERMs/_index.md
> +[^2]: 见维基百科相应条目
抱歉，我刚才以为你是指第 67 行。

2023-08-15 10:07 UTC, Bersella-AI requested changes
剩下一些小问题，旁的基本具备合并条件了。:+1:

2023-08-15 10:07 UTC, Bersella-AI commented on content/zh-cn/docs/medicine/SERMs/raloxifene/index.md
> +值得注意的是，不同于雌二醇，雷洛昔芬无抗促性腺激素作用[^4]，因此其不可与孕激素联合来充分降低雄激素水平。而单独使用孕激素只可降低睾酮水平至约 50%[^6]，螺内酯不能有效拮抗高水平的雄激素[^7]。该方案下，一般的抗雄激素疗法（CPA 或螺内酯，皆需与雌激素合用）不适用。
根据 Transfeminine Science 所作[文章](https://tfsci.mtf.wiki/zh-cn/articles/cpa-dosage/)，醋酸环丙孕酮单药至多可降低 70% 左右的睾酮水平，文献中普遍分布于 50～70%。
此处引用的有关螺内酯的文章已被[翻译](https://tfsci.mtf.wiki/zh-cn/articles/spiro-testosterone/)。

2023-08-15 12:45 UTC, wmtdru8xip commented on content/zh-cn/docs/medicine/SERMs/raloxifene/index.md
> +1. 药物相互作用：**TODO**
（这几天真的很忙，所以我把牌子撤了...）

2023-08-15 12:47 UTC, wmtdru8xip commented
好的，我已将其修正。

2023-08-16 05:52 UTC, Bersella-AI requested changes

2023-08-16 05:52 UTC, Bersella-AI commented on content/zh-cn/docs/medicine/SERMs/raloxifene/index.md
> +值得注意的是，不同于雌二醇，雷洛昔芬无抗促性腺激素作用[^4]，因此其不可与孕激素联合来充分降低雄激素水平。而单独使用孕激素只可降低睾酮水平至约 50%-70%，且长期使用下睾酮水平会发生一定程度的回升[^6]，螺内酯不能有效拮抗高水平的雄激素[^7]。该方案下，一般的抗雄激素疗法（CPA 或螺内酯，皆需与雌激素合用）不适用。
注意：不能用“至约”，这种说法下降幅仅 30～50%，与引用资料不符。

2023-08-16 06:11 UTC, wmtdru8xip commented on content/zh-cn/docs/medicine/SERMs/raloxifene/index.md
> +值得注意的是，不同于雌二醇，雷洛昔芬无抗促性腺激素作用[^4]，因此其不可与孕激素联合来充分降低雄激素水平。而单独使用孕激素只可降低睾酮水平至约 50%-70%，且长期使用下睾酮水平会发生一定程度的回升[^6]，螺内酯不能有效拮抗高水平的雄激素[^7]。该方案下，一般的抗雄激素疗法（CPA 或螺内酯，皆需与雌激素合用）不适用。
对不起，是笔误。

2023-08-18 08:26 UTC, wmtdru8xip commented
@Bersella-AI 我已修正笔误，请再次检查一下，谢谢。

2023-08-18 10:04 UTC, Bersella-AI submitted a review, later dismissed
做得不错！翔实而且接近专业！鉴于“药物相互作用”尚未完成，我可能会按说明书内容进行补充，如果你希望自行增补，请留言备忘。

2023-08-18 10:07 UTC, Bersella-AI approved these changes

2023-08-20 14:03 UTC, wmtdru8xip commented
@septs 请 review 一下，好吗？谢谢。

2023-08-20 14:05 UTC, septs commented on content/zh-cn/docs/medicine/SERMs/_index.md
> +<!-- ((?<=[0-9a-zA-Z])(?=[一-龥])|(?<=[一-龥])(?=[0-9a-zA-Z])) -->
可以移除这个吗？

2023-08-20 14:06 UTC, septs commented on content/zh-cn/docs/medicine/SERMs/_index.md
> +<!-- TODO: skin & body composition & "?"
此注释的功能目的是？

2023-08-20 14:10 UTC, septs commented
@Bersella-AI 是否考虑邀请 @wmtdru8xip 为 tfsci.mtf.wiki 提供帮助？

2023-08-20 14:23 UTC, saeziae approved these changes

2023-08-20 14:25 UTC, saeziae commented
lgtm

解释清上面的疑问后尽快合并

2023-08-21 01:54 UTC, wmtdru8xip commented on content/zh-cn/docs/medicine/SERMs/_index.md
> +<!-- TODO: skin & body composition & "?"
> 诸如 SHBG、IGF-1 等专业、非相关术语缩写，应予以解释。

Bersella-AI 要求我对其进行解释。

2023-08-21 02:32 UTC, septs commented on content/zh-cn/docs/medicine/SERMs/_index.md
> +<!-- TODO: skin & body composition & "?"
我指的是这行 HTML 注释

2023-08-21 02:58 UTC, septs commented on content/zh-cn/docs/medicine/SERMs/_index.md
> +注：SHBG - sex hormone binding globulin / 性激素结合球蛋白，一种主要与性激素，尤其是雄激素结合的血浆蛋白；IGF-1 - insulin-like growth factor 1 / 类胰岛素生长因子 1，一种受 GH（生长激素）调控的，主要通过肝脏内分泌与各组织旁分泌 / 自分泌的肽类激素；是发挥 GH 作用的主要激素
```suggestion
注：

SHBG - sex hormone binding globulin
: 性激素结合球蛋白，一种主要与性激素，尤其是雄激素结合的血浆蛋白

IGF-1 - insulin-like growth factor 1
: 类胰岛素生长因子 1，一种受 GH（生长激素）调控的，主要通过肝脏内分泌与各组织旁分泌

自分泌的肽类激素
: 是发挥 GH 作用的主要激素
```

see https://www.markdownguide.org/extended-syntax/#definition-lists
see https://www.markdownguide.org/tools/hugo/

2023-08-21 03:00 UTC, septs commented on content/zh-cn/docs/medicine/SERMs/_index.md
> +注：SHBG - sex hormone binding globulin / 性激素结合球蛋白，一种主要与性激素，尤其是雄激素结合的血浆蛋白；IGF-1 - insulin-like growth factor 1 / 类胰岛素生长因子 1，一种受 GH（生长激素）调控的，主要通过肝脏内分泌与各组织旁分泌 / 自分泌的肽类激素；是发挥 GH 作用的主要激素
可以使用 Definition Lists 改善可维护性

2023-08-21 04:37 UTC, wmtdru8xip commented on content/zh-cn/docs/medicine/SERMs/_index.md
> +<!-- TODO: skin & body composition & "?"
噢，那个是记录我此后拓充表格时会用到的 query。

2023-08-21 04:42 UTC, septs approved these changes

2023-08-21 04:42 UTC, merged