更新雌二醇凝胶使用方法
project-trans/MtF-wiki pull request #889
Opened 2023-09-10 03:09 UTC by LiAlH4-Tr

根据刘烨的建议

2023-09-10 03:58 UTC, Cryolitia commented
@LiAlH4-Tr 刘烨的建议有任何依据吗，根据 https://tfsci.mtf.wiki/zh-cn/articles/genital-e2-application/ 我建议涂抹蛋皮，但是蛋皮怎么更换

cc @Bersella

2023-09-10 04:01 UTC, Cryolitia commented
@LiAlH4-Tr 我认为这部分内容更恰当的修改方式是，单独另起几段

> 有部分医生提出建议经常更换涂抹位置

> 根据 <url> ，涂抹在阴囊/新阴唇可获得最佳效果

2023-09-10 04:02 UTC, Cryolitia requested changes

2023-09-10 04:02 UTC, Cryolitia commented on content/zh-cn/docs/medicine/estrogen/gel/index.md
> +皮肤外用，每天 1-2 计量尺，即 2.5g-5g 凝胶。涂抹于易于吸收且方便日常活动的部位（如下腹部、大腿上部），无需揉搓，药品不污染衣物。尽量涂抹在较大面积的皮肤上，并且厚度越小越好，这样更有利于吸收。不要同时涂抹在多处皮肤（如同时涂抹于大腿、手臂、腹部）。建议不要一直涂抹一个地方，而是在一段时间后更换涂抹位置。
在我approve前暂时不要合并

2023-09-10 04:05 UTC, LiAlH4-Tr commented
> @LiAlH4-Tr 刘烨的建议有任何依据吗，根据 https://tfsci.mtf.wiki/zh-cn/articles/genital-e2-application/ 我建议涂抹蛋皮，但是蛋皮怎么更换
> 
> cc @Bersella-AI

似乎涂蛋皮会增加致癌风险

2023-09-10 04:06 UTC, Cryolitia commented
@LiAlH4-Tr 你有没有哪怕认真读一下我发的那个文章

2023-09-10 04:11 UTC, LiAlH4-Tr commented
> @LiAlH4-Tr 你有没有哪怕认真读一下我发的那个文章

抱歉刚才才读，文章内并没有提及致癌风险，不过我在其他地方有听说

2023-09-10 04:11 UTC, Cryolitia commented
@LiAlH4-Tr 你有没有哪怕认真读一下我发的那个文章！

听谁说的，点名道姓列参考文献出来

2023-09-10 04:30 UTC, LiAlH4-Tr commented
> @LiAlH4-Tr 你有没有哪怕认真读一下我发的那个文章！
> 
> 听谁说的，点名道姓列参考文献出来

抱歉，是我之前读文章不仔细了，目前已增加建议的内容

2023-09-10 09:43 UTC, Bersella-AI reviewed
关于涂抹部位是否需轮换，由于现有说明书资料不足，我特意去找了经美国 FDA 批准的雌二醇凝胶，找到了这份说明书：<https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/021166s018lbl.pdf>
文末详细介绍了凝胶用法，其中关于涂抹部位的事项仅提到“不得用于**乳房或阴道内及阴道周围**”和“尽量摊薄于**手腕至肩膀之间内侧、外侧一切部位**”；虽未提及是否需轮换，但从这份说明看，涂抹部位仅限于手臂，故无需轮换也是可以接受的。

至于外生殖器使用凝胶，可以肯定的是，**前列腺和睾丸对雌激素不敏感**，也便基本不存在因雌激素致癌的风险。这方面没有正式的临床研究，但观察性研究表明接受 GAHT 之后前列腺癌风险大幅降低（当然并非完全消失，见 Transfem Science《[激素治疗指南](https://tfsci.mtf.wiki/zh-cn/articles/transfem-intro/#monitoring-of-therapy)》末尾）。即使如此，社群当中这方面的争议仍然较大。基于以上考量，**我不支持将此纳入 Wiki，而应当给读者以自行探索的空间。**

2023-09-10 10:00 UTC, Cryolitia commented
> 关于涂抹部位是否需轮换，由于现有说明书资料不足，我特意去找了经美国 FDA 批准的雌二醇凝胶，找到了这份说明书：https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/021166s018lbl.pdf 文末详细介绍了凝胶用法，其中关于涂抹部位的事项仅提到“不得用于**乳房或阴道内及阴道周围**”和“尽量摊薄于**手腕至肩膀之间内侧、外侧一切部位**”；虽未提及是否需轮换，但从这份说明看，涂抹部位仅限于手臂，故无需轮换也是可以接受的。
> 
> 至于外生殖器使用凝胶，可以肯定的是，**前列腺和睾丸对雌激素不敏感**，也便基本不存在因雌激素致癌的风险。这方面没有正式的临床研究，但观察性研究表明接受 GAHT 之后前列腺癌风险大幅降低（当然并非完全消失，见 Transfem Science《[激素治疗指南](https://tfsci.mtf.wiki/zh-cn/articles/transfem-intro/#monitoring-of-therapy)》末尾）。即使如此，社群当中这方面的争议仍然较大。基于以上考量，**我不支持将此纳入 Wiki，而应当给读者以自行探索的空间。**

FDA提到不得用于阴道周围是什么考虑，是否适用于 SRS 后的跨性别女性。

2023-09-10 10:05 UTC, Bersella-AI commented
> FDA提到不得用于阴道周围是什么考虑，是否适用于 SRS 后的跨性别女性。

可以认为该说明书的对象仅限于**有原生阴道、子宫、卵巢等的顺性别妇女**，其性器官对雌激素敏感。而原生男性的性器官对雄激素敏感，只有在胚胎器官分化期时可能会受雌激素影响，其它情况下雌激素影响甚微；即使是治疗前列腺癌，也是通过对 HPG 轴的负反馈调节才做到的，对睾丸只有间接抑制作用。

2023-09-10 10:19 UTC, Bersella-AI commented
对跨性别女性而言，即使经过*完整* 性别重置手术，再造阴道和阴唇等时取用的材料也基本源于肠道或原外生殖器，基本不对雌激素敏感，也便不存在原生阴道所造成的限制，致癌性更无从谈起。但是，还是那个理，**众口难调**也。

2023-09-13 18:19 UTC, Cryolitia requested changes

2023-09-13 18:19 UTC, Cryolitia commented on content/zh-cn/docs/medicine/estrogen/gel/index.md
> +[据此](https://tfsci.mtf.wiki/zh-cn/articles/genital-e2-application/) ，涂抹在阴囊/新阴唇可获得最佳效果
根据 @Bersella-AI 的意见，51行也删掉吧。
```suggestion

```

2023-09-17 19:19 UTC, RimuroSuraimu commented
看了下我用的凝胶说明书：
`Das Gel sollte nach dem Waschen, vorzugsweise morgens oder abends, auf eine möglichst große, saubere, trockene und intakte Hautfläche aufgetragen werden. Hierfür bevorzugte Körperstellen sind Arme, Schultern, Bauch oder Oberschenkel. Das Gel darf nicht auf die Brüste oder Schleimhäute aufgebracht werden, weiterhin ist der Kontakt mit den Augen zu vermeiden. Mit dem Überziehen von Kleidung sollte bis nach dem Eintrocknen gewartet werden. Waschen Sie nach der Anwendung gründlich die Hände.`

凝胶应该在洗净之后，最好在早上或者晚上，在一个面积尽量大，干净，干燥而且完好的皮肤表面使用。对此所用到的身体部分是：手臂，肩膀，腹部，大腿。凝胶不可以在乳房或者黏膜上使用，除此之外井盖防止接触眼睛。干燥后才应该穿上衣服。
涂抹凝胶后请仔细洗手。

2023-09-18 15:40 UTC, Cryolitia commented
建议根据 @RimuroSuraimu 提供的说明书选段重写此段内容。

另外可考虑将德国凝胶说明书翻译至 tfsci

2023-09-19 15:50 UTC, RimuroSuraimu commented
will do

2023-09-26 04:28 UTC, Cryolitia commented
烦请 @Bersella-AI @RimuroSuraimu 拨冗根据 Timeline 整理更新主站和tfsci相关内容，非常感谢。本 Pull Request 将保持开放以备忘未尽之事。

2024-03-04 09:11 UTC, Bersella-AI commented
这两天整理了一些资料，其中包括 4 份凝胶说明书和 4 份公开文献：

1. [雌二醇凝胶（爱斯妥）说明书](https://tfsci.mtf.wiki/misc/oestrogel/)
2. ASCEND Therapeutics. Prescribing Information, Patient Information & Instructions for Use: Estrogel&reg; 0.06% [EB/OL]. *Drugs@FDA*, 2023. 译文：《[雌二醇凝胶（美国 EstroGel）说明书](https://tfsci.mtf.wiki/misc/estrogel-us/)》
3. Besins Healthcare Germany GmbH. FACHINFORMATION: Gynokadin® Dosiergel [EB/OL]. (2023-07). <https://service.besins-healthcare.de/gynokadin/fi/gynokadin-dosiergel-fachinformation-besins-healthcare.pdf>——注，此文即 @ArtsSuraimu 所引德国凝胶产品 Gynokadin 之处方说明书
4. Organon. Patient medication information: ESTROGEL&reg; [EB/OL]. (2023-08-29). <https://pdf.hres.ca/dpd_pm/00072270.PDF> ——注：此文即 PR #929 所引加拿大 Organon 公司凝胶产品 Estrogel 之说明书
5. Järvinen A, Granander M, Nykänen S, et al. Steady-state pharmacokinetics of oestradiol gel in post-menopausal women: effects of application area and washing [J]. *British Journal of Obstetrics and Gynaecology*, 1997, 104(Suppl 16): 14-18. DOI: [10.1111/j.1471-0528.1997.tb11562.x](https://doi.org/10.1111/j.1471-0528.1997.tb11562.x)
6. Naunton M, Al Hadithy A F Y, Brouwers J R B J, et al. Estradiol gel: review of the pharmacology, pharmacokinetics, efficacy, and safety in menopausal women [J]. *Menopause*, 2006, 13(3): 517-527. DOI: [10.1097/01.gme.0000191881.52175.8c](https://doi.org/10.1097/01.gme.0000191881.52175.8c)
7. Järvinen A, Bäckström A-C, Elfström C, et al. Comparative absorption and variability in absorption of estradiol from a transdermal gel and a novel matrix-type transdermal patch [J]. *Maturitas*, 2001, 38(2): 189-196. DOI: [10.1016/S0378-5122(00)00222-X](https://doi.org/10.1016/S0378-5122(00)00222-X)
8. Nina Dragićević, Howard I. Maibach. Percutaneous Absorption: Drugs, Cosmetics, Mechanisms, Methods [M]. 5th ed. Boca Raton, US: CRC Press, 2021: 175-190.

收集以上资料旨在确立恰当的用法用量，例如用药时机、用药部位、用药面积、是否轮换、每日剂量等，并寻找其它有实证的信息。其中：

- 关于是否应轮换用药部位，诸说明书均未明确提及或仅推荐用于手臂/上臂/肩膀，而后者是除“爱斯妥”以外各说明书均推荐的唯一部位。但是，考虑到个别人的皮肤可能对水—乙醇凝胶起反应（作为不良反应列于资料 1、2 和 6），故轮换部位是有一定意义的。因此，使用凝胶时，**可酌情**决定是否轮换用药部位。
- 关于部位的选择，资料 8 可知上外臂、背部/肩膀、胸上部和臀部对雌二醇、睾酮等甾体激素的吸收率大体一致。如前所述，外生殖器（阴囊）用药尚存争议，故不在讨论范围内。
- 关于用药面积，以上说明书（资料 1～4）均推荐“用于较大面积的皮肤”或“（尽量）摊薄”。但是，资料 5 的研究结果不支持这个观点，其中小面积用药后的雌二醇浓度峰值和累积剂量（AUC）均高于大面积用药。
- 关于用药时机，说明书提示较完备，其中资料 2 推荐早晨或晚上用药。
- 关于剂量，半尺（1.25 g/0.75mg）适用于顺性别女性更年期相关症状的管理，但对跨性别女性而言过少，实际以一尺（2.5g/1.5 mg）为基础剂量。经资料 1、3 和 6 佐证，用于上臂时，该剂量可维持血药浓度在 60～80 pg/mL 的平均值，剔除基底值后，基本符合《[雌二醇在不同途径下的大致等效剂量](https://tfsci.mtf.wiki/articles/e2-equivalent-doses/)》当中“低剂量”可维持的浓度。
- 不良反应中，腹泻、皮肤疾病和流感样症状等可见于资料 6，但未被 wiki 收录。
- 资料 6 明确标定半衰期为 36.5 小时。

我将基于上述发现，重新编排“用法用量”部分。

2024-03-09 09:26 UTC, Bersella-AI commented
今日已更新用法用量和注意事项（<https://github.com/project-trans/MtF-wiki/commit/79dcbf64adf66ebd23e10bd697da8376476a021b>）。更新前，我再次检索文献，试图寻找支持将雌二醇凝胶用于大面积皮肤的**临床研究**（关键字是 “effects of application site on estradiol gel” 或 “topical application of estradiol on different areas”），但未果；动物试验和睾酮凝胶研究方面倒是有所收获：

- Chanez J F,  de Lignières B, Marty J P, et al. Influence of the Size of the Area of Treatment on Percutaneous Absorption of Estradiol in the Rat [J]. *Skin Pharmacology*, 1989, 2(1): 15-21. DOI: [10.1159/000210797](https://doi.org/10.1159/000210797)
- Wang C, Berman N, Longstreth J A, et al. Pharmacokinetics of Transdermal Testosterone Gel in Hypogonadal Men: Application of Gel at One Site Versus Four Sites: A General Clinical Research Center Study [J]. *The Journal of Clinical Endocrinology & Metabolism*, 2000, 85(3): 964-969. DOI: [10.1210/jcem.85.3.6437](https://doi.org/10.1210/jcem.85.3.6437)

虽然考虑到睾酮在化学结构上和雌二醇近似，可经皮吸收，将其结论推导至雌二醇凝胶上并无不妥，动物试验也会一定程度反映药物对人体的作用；但是，关于睾酮或动物的结果远不及**雌二醇在人体上的表现有说服力**。所以，我目前尚不能就用药面积对雌二醇经皮吸收之影响给出可靠的意见，唯有如实陈述文献检索结果。  
当然，我们仍然欢迎各位读者分享更多使用经验和可靠的文献来源，帮助我们改进 wiki。再次感谢 @XingLiAl 的投稿。

2024-03-30 06:31 UTC, Bersella-AI commented
由于主线已合并本 PR 所增加内容（https://github.com/project-trans/MtF-wiki/commit/79dcbf64adf66ebd23e10bd697da8376476a021b ），现对本 PR 予以关闭。如有未竟事宜（例如新发现支持轮换用药部位的公开文献或产品说明书，有其他医师支持，确认某些部位用药的安全性等），可提交新 Issue 共同讨论。对于药品说明书的翻译，可移步 [TFSci](https://github.com/project-trans/transfeminine-science) 翻译项目。

2024-03-30 06:31 UTC, closed without merging