📝 增加无法修改学历时可采取的对策
project-trans/MtF-wiki pull request #891
Opened 2023-09-12 15:55 UTC by BeiyanYunyi

#819 https://github.com/project-trans/MtF-wiki/issues/819#issuecomment-1714924528

谨以此 PR 纪念我的小学同学 [Mio](https://one-among.us/profile/Mio/)。

由于是第一次对 MtF Wiki 进行实质性内容贡献，当前 PR 存在一些问题：

- `{{< mtf-wiki >}} 暂未检索到相关部门对“禁止毕业学历修改”的明文规定。` 这样的内容是否合适？
- 在“我们仍有许多对策可供选择”后，引用了[推特内容](https://twitter.com/floria_nyan/status/1599022728526594048)，需要征得许可。
- 为了劝解而增加的“可采取的对策”折叠框具有“反而加剧焦虑”的可能性，需要经过多人审阅斟酌。

2023-09-13 09:04 UTC, saeziae requested changes
内容无问题。待确认细节

2023-09-13 09:04 UTC, saeziae commented on content/zh-cn/docs/srs/education.md
> +{{< expand "可采取的对策" >}}
此处使用 expand 是否必要？

2023-09-13 09:35 UTC, BeiyanYunyi commented on content/zh-cn/docs/srs/education.md
> +{{< expand "可采取的对策" >}}
我担心这段提示篇幅过长，反而“欲盖弥彰”，起到加剧焦虑的作用

2023-09-13 09:51 UTC, septs commented on content/zh-cn/docs/srs/education.md
> +- 也可以考虑使用 LinkedIn 等途径寻找国外的工作。
严格来说，“外国”需要作出限定（指“民主国家”）

可以引用 https://zh.wikipedia.org/zh-cn/各地LGBT权利 给读者自行评估

2023-09-13 10:00 UTC, BeiyanYunyi commented on content/zh-cn/docs/srs/education.md
> +- 也可以考虑使用 LinkedIn 等途径寻找国外的工作。
1103990 如何

2023-09-13 18:27 UTC, Cryolitia commented on content/zh-cn/docs/srs/education.md
> +- 也可以考虑使用 LinkedIn 等途径寻找国外的工作。
> 严格来说，“外国”需要作出限定（指“民主国家”）
> 
> 可以引用 [https://zh.wikipedia.org/zh-cn/各地LGBT权利](https://zh.wikipedia.org/zh-cn/%E5%90%84%E5%9C%B0LGBT%E6%9D%83%E5%88%A9) 给读者自行评估

差不多得了 /流汗黄豆

2023-09-13 18:31 UTC, Cryolitia commented on content/zh-cn/docs/srs/education.md
> +{{< mtf-wiki >}} 暂未检索到相关部门对“禁止毕业学历修改”的明文规定。以下是原“学历修改”内容：
https://github.com/project-trans/MtF-wiki/issues/819#issuecomment-1627664418

我觉得根据人民法院报几乎可以确认是无法修改了

2023-09-13 18:32 UTC, Cryolitia commented
> * 在“我们仍有许多对策可供选择”后，引用了[推特内容](https://twitter.com/floria_nyan/status/1599022728526594048)，需要征得许可。

这种情况最好给对方Co-Author

2023-09-14 06:31 UTC, BeiyanYunyi commented on content/zh-cn/docs/srs/education.md
> +{{< mtf-wiki >}} 暂未检索到相关部门对“禁止毕业学历修改”的明文规定。以下是原“学历修改”内容：
35ef7b5

2023-09-14 06:32 UTC, BeiyanYunyi commented
> 这种情况最好给对方Co-Author

是指在推特上联系对方，邀请其来 GitHub 提意见吗？

2023-10-05 08:06 UTC, cocoAutumn commented
> 以新的户籍获得更高级别的学历学位，并在之后只使用这一学历学位。

实测可行，本人的户籍性别和姓名是在硕士毕业前一两个月内才修改的。

2023-10-08 08:40 UTC, fluoria commented
不好意思我之前没有看到推上的私信。请随意使用。
我个人的看法主要是认为应该对目前教育部的态度予以明确，避免让人产生“毕业后改学历只是比较难”、“还是有流程可以做到的”这样的误解，进而对相关决策造成影响。如有需要我可以提供我保留的电话录音等证据，而且大家其实也都可以联系教育部门对消息进行验证。

2023-10-14 03:56 UTC, BeiyanYunyi commented
> 不好意思我之前没有看到推上的私信。请随意使用。 我个人的看法主要是认为应该对目前教育部的态度予以明确，避免让人产生“毕业后改学历只是比较难”、“还是有流程可以做到的”这样的误解，进而对相关决策造成影响。如有需要我可以提供我保留的电话录音等证据，而且大家其实也都可以联系教育部门对消息进行验证。

https://github.com/project-trans/MtF-wiki/pull/891/commits/b48136eb3e625fc0522b80f0265d0b43e86cc0a7 这个修改如何

2023-10-28 16:17 UTC, saeziae approved these changes

2023-10-28 16:19 UTC, merged