[O] Use two methods to calculate cup size
project-trans/MtF-wiki pull request #919
Opened 2023-10-23 00:32 UTC by LS-KR

现在是两种方法都有了（

2023-10-23 00:33 UTC, Cryolitia commented
link #915

Look Better To Me

2023-10-23 00:34 UTC, Cryolitia approved these changes

2023-10-23 01:43 UTC, saeziae requested changes

2023-10-23 01:43 UTC, saeziae commented on content/zh-cn/cup-calculator.md
> +<p id="resultcn">国内罩杯: </p>
```suggestion
<p id="resultcn">中国尺码: </p>
```

2023-10-23 01:43 UTC, saeziae commented on content/zh-hant/cup-calculator.md
> +      cup = "AA，买少女小背心去吧";
```suggestion
      cup = "AA，購買少女內衣";
```

疑似誤改原文繁中。

2023-10-23 01:43 UTC, saeziae commented on content/zh-hant/cup-calculator.md
> +<p id="resultcn">國內罩杯: </p>
```suggestion
<p id="resultcn">中國尺碼: </p>
```

2023-10-23 01:43 UTC, saeziae commented on content/zh-cn/cup-calculator.md
> +国内罩杯计算方法:
```suggestion
中国尺码计算方法:
```

2023-10-23 01:43 UTC, saeziae commented on content/zh-hant/cup-calculator.md
> +國內罩杯尺碼計算方法:
```suggestion
中國尺碼計算方法:
```

2023-10-23 01:45 UTC, LS-KR commented on content/zh-hant/cup-calculator.md
> +      cup = "AA，买少女小背心去吧";
~~复制粘贴出的问题~~

2023-10-23 01:46 UTC, saeziae approved these changes
LBTM, too

2023-10-23 02:07 UTC, BeiyanYunyi approved these changes

2023-10-23 02:07 UTC, merged

2023-10-23 02:08 UTC, Artoria2e5 commented
不，+11 那个算法应该直接删掉。

首先维基百科不是好到哪里去的来源，原文甚至没 reference。其次 11 围差挪到下胸围的做法是基于过时的 [Underbust +4](https://en.wikipedia.org/wiki/Bra_size#Underbust_+4) 算法，已经被 Kohl 和国内专业的奶糖派抛弃。+4 的算法会系统性地低估罩杯、高估上胸围，无论是消费者经验还是[White & Scurr 2012](https://sci-hub.se/https://www.tandfonline.com/doi/abs/10.1080/00140139.2011.647096)都有这个结论。

2023-10-23 02:08 UTC, Artoria2e5 commented
md 怎么就 merge了？

2023-10-23 02:10 UTC, septs commented
这么说，wikipedia 上的提供的参考也需要更新

2023-10-23 02:10 UTC, Artoria2e5 commented
Wikipedia 压根就没有参考，完全可以作为 unreferenced 全删了。

2023-10-23 02:13 UTC, Artoria2e5 commented
更带劲的是这个PR的两个方法甚至还是坏的，对中国的计算仍然保留了瞎搞的 11cm 处理。能用 git history 功能看看 https://github.com/LS-KR/MtF-wiki/blob/22ba3837b63be3ec251b3361574553980756726b/content/zh-cn/cup-calculator.md?plain=1 原来的版本吗？

2023-10-23 02:17 UTC, Artoria2e5 commented
站住别动，我喝一罐 monster 来修。

2023-10-23 02:20 UTC, septs commented
这让我想起个梗

https://twitter.com/Bitturing/status/1676432842006614017

2023-10-23 02:35 UTC, saeziae commented
> 能用 git history 功能看看原来的版本吗

原来的版本是我写的，照抄的中国购物网站常见的尺码表，他们说结果偏大（

2023-10-23 02:39 UTC, Artoria2e5 commented
因为文胸尺码本来就是很狂野西部的东西，各种瞎来的算法加上瞎搞的厂商

2023-10-23 02:43 UTC, Artoria2e5 commented
好烦，https://www.reddit.com/r/ABraThatFits/wiki/mtfguide/ 提到 AMAB 胸型需要额外调整

2023-10-28 16:05 UTC, Cryolitia commented
相关 PR 已经全部回退，请移至 #925 进一步讨论。