增加Organon雌二醇，在加拿大HRT的注意事项。
project-trans/MtF-wiki pull request #929
Opened 2023-11-03 20:56 UTC by MikuMikuMe

1. 增加了由ORGANON CANADA INC.生产的[雌二醇](https://health-products.canada.ca/dpd-bdpp/search-fast-recherche-rapide?lang=eng&code=17859)
2. 列出一些在加拿大HRT的事项以此来提醒部分学生。

2023-11-03 21:02 UTC, Cryolitia requested changes

2023-11-03 21:02 UTC, Cryolitia commented on content/zh-cn/docs/hrt/canada/注意事项/index.md
> +---
路径名不要有中文

2023-11-03 21:07 UTC, Cryolitia commented
CC @RimuroSuraimu 是不是你正在用的那种

2023-11-03 22:07 UTC, MikuMikuMe commented on content/zh-cn/docs/hrt/canada/注意事项/index.md
> +---
OK了

2023-11-06 04:06 UTC, Bersella-AI requested changes
认可 Organon Estrogel 作为雌二醇凝胶制剂之一列入。有几处小问题，烦请参考复查。

2023-11-06 04:06 UTC, Bersella-AI commented on content/zh-cn/docs/medicine/estrogen/gel/index.md
> +- [药物专著](https://www.organon.com/canada-en/wp-content/uploads/sites/5/2021/05/ESTROGEL-PM_E.pdf)
`ESTROGEL-CI_E.pdf` 仅含供患者参考的说明书内容，以“患者用说明书”标注之。
`ESTROGEL-PM_E.pdf` 除患者用说明书以外，还包含专家用说明书，且 Monograph 之字面意“专著”在此不通顺，建议以“说明书全文”指代。同时，其链接可考虑引用[加拿大卫生部药品数据库文件](https://pdf.hres.ca/dpd_pm/00072270.PDF)。

2023-11-06 07:31 UTC, MikuMikuMe commented on content/zh-cn/docs/medicine/estrogen/gel/index.md
> +- [药物专著](https://www.organon.com/canada-en/wp-content/uploads/sites/5/2021/05/ESTROGEL-PM_E.pdf)
Done

2023-11-06 07:31 UTC, MikuMikuMe commented on content/zh-cn/docs/medicine/estrogen/gel/index.md
> +皮肤外用，每天 1-2 计量尺(2-4泵)，即 2.5g-5g 凝胶。涂抹于易于吸收且方便日常活动的部位（如下腹部、大腿上部），尽量涂抹在较大面积的皮肤上，并且厚度越小越好，这样更有利于吸收，但不要同时涂抹在多处皮肤（如同时涂抹于大腿、手臂、腹部）。无需揉搓，药品不污染衣物。
Done

2023-11-06 07:31 UTC, MikuMikuMe commented on content/zh-cn/docs/medicine/estrogen/gel/index.md
> +- 生产企业：Organo Canada Inc.
Done

2023-11-06 15:53 UTC, Bersella-AI approved these changes
好的，非常感谢！我仅负责药物板块，其余需我的同事审议通过。考虑将来和 Gynokadin 等品牌/厂家不同、但剂型/用法相似且见于中国大陆以外的制剂一并介绍。

2023-11-10 02:44 UTC, Cryolitia approved these changes

2023-11-11 16:08 UTC, RimuroSuraimu commented
> CC @RimuroSuraimu 是不是你正在用的那种

其实不是，咱用的是Gynokadin - 是比利时生产的德国分销的

2023-11-11 16:17 UTC, merged

2023-11-11 16:17 UTC, Cryolitia commented
说明书可以考虑翻译一下 @Bersella-AI