更新 上海四一一
project-trans/MtF-wiki pull request #930
Opened 2023-11-06 05:23 UTC by smzkaede

### 2023年11月住院更新
- 凡士林纱布数量
询问护士站确认，需15~20片，手术中和术后护理都需要使用
- 餐具问题两处
携带物品准备、住院餐食详情
- 水壶建议
携带物品准备
- 术前陪护不可过夜
入院后护士宣教
- 入院检查相关

2023-11-10 02:41 UTC, Cryolitia requested changes

2023-11-10 02:41 UTC, Cryolitia commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +- 电源插排
这里空格是为了同一个无序列表项内换行，不能删除

2023-11-10 02:42 UTC, Cryolitia requested changes

2023-11-10 02:42 UTC, Cryolitia commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +- 粗网灭菌凡士林纱布 25×40cm 2包（规格一般为1包10片，至少需要15片，推荐15~20片）
下方链接购买一包足够

2023-11-10 02:43 UTC, Cryolitia commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +- 粗网灭菌凡士林纱布 25×40cm 2包（规格一般为1包10片，至少需要15片，推荐15~20片）
CC @BeiyanYunyi 再次确认需要几包，明确是否自暑假后变更要求

2023-11-11 06:33 UTC, BeiyanYunyi commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +- 粗网灭菌凡士林纱布 25×40cm 2包（规格一般为1包10片，至少需要15片，推荐15~20片）
目前问了 2 个在住院的mtf，都说被要求按15片准备，有的人会两人拼三盒

2023-11-11 06:44 UTC, BeiyanYunyi commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +- 结扎精索，每侧各十分钟
```suggestion
- 结扎精索，每侧各十分钟  
```

2023-11-11 06:44 UTC, BeiyanYunyi commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +- 设计阴蒂，分离阴蒂血管神经至阴茎根部，截断并结扎海绵体，一小时
```suggestion
- 设计阴蒂，分离阴蒂血管神经至阴茎根部，截断并结扎海绵体，一小时  
```

2023-11-11 06:44 UTC, BeiyanYunyi commented on content/zh-cn/docs/srs/china/sh411/_index.md
>    最容易松脱，会使用 7 号缝线进行结扎
```suggestion
  最容易松脱，会使用 7 号缝线进行结扎  
```

2023-11-12 00:37 UTC, Cryolitia approved these changes

2023-11-12 00:37 UTC, BeiyanYunyi approved these changes

2023-11-12 00:37 UTC, merged