Create 苏州市立医院北区HRT
project-trans/MtF-wiki pull request #953
Opened 2023-12-14 15:19 UTC by Baizhi-Angelica

第一次学习使用GitHub，如果有任何格式或者规则错误，请大佬们斧正！顺便在心里骂我一万遍！
之前提交了issue，看到pull request好像不那么难，就想试一下。
如果可以的话还请大佬们把苏州文件夹合并一下吧

2023-12-14 15:24 UTC, Clansty commented on content/zh-cn/docs/hrt/Suzhou/luting/index.md
> +### 以 CC-BY-SA 4.0 协议分发
这个应该加到内页里嘛（（

2023-12-14 15:25 UTC, Clansty commented on content/zh-cn/docs/hrt/Suzhou/luting/index.md
> +![2023-12-14 173330](https://github.com/project-trans/MtF-wiki/assets/52900290/204fc8dd-05cf-43c8-a810-d35f6641c932)
这个需不需要设置图片的标题qwq

2023-12-14 15:26 UTC, Baizhi-Angelica commented on content/zh-cn/docs/hrt/Suzhou/luting/index.md
> +![2023-12-14 173330](https://github.com/project-trans/MtF-wiki/assets/52900290/204fc8dd-05cf-43c8-a810-d35f6641c932)
我去谷歌一下怎么设置，稍等

2023-12-14 15:27 UTC, Baizhi-Angelica commented on content/zh-cn/docs/hrt/Suzhou/luting/index.md
> +### 以 CC-BY-SA 4.0 协议分发
马上删！

2023-12-14 15:27 UTC, Clansty commented on content/zh-cn/docs/hrt/Suzhou/luting/index.md
> +![2023-12-14 173330](https://github.com/project-trans/MtF-wiki/assets/52900290/204fc8dd-05cf-43c8-a810-d35f6641c932)
```suggestion
![收费票据](https://github.com/project-trans/MtF-wiki/assets/52900290/204fc8dd-05cf-43c8-a810-d35f6641c932)
```

2023-12-14 15:27 UTC, Clansty commented on content/zh-cn/docs/hrt/Suzhou/luting/index.md
> +![IMG_5428](https://github.com/project-trans/MtF-wiki/assets/52900290/5eb78d63-f4e5-4b11-86b5-42ca694af4ea)
```suggestion
![开出的补佳乐](https://github.com/project-trans/MtF-wiki/assets/52900290/5eb78d63-f4e5-4b11-86b5-42ca694af4ea)
```

2023-12-14 15:36 UTC, Baizhi-Angelica commented
需要添加一个HRT的Label，但是没找到在哪里添加…

2023-12-14 15:39 UTC, Baizhi-Angelica commented
谢谢@[CoelacanthusHex](https://github.com/CoelacanthusHex) CoelacanthusHex大佬添加的标签☺️。请原谅我的无知

2023-12-14 15:42 UTC, CoelacanthusHex commented
> 谢谢@[CoelacanthusHex](https://github.com/CoelacanthusHex) CoelacanthusHex大佬添加的标签☺️。请原谅我的无知

没事，好像是自动 label 的规则写的有点问题

2023-12-15 01:43 UTC, Clansty commented on content/zh-cn/docs/hrt/Suzhou/luting/index.md
> +---
等一下

这里的竖线是 `| `，而 wiki 上别的页面好像是`｜`

2023-12-15 01:44 UTC, Clansty requested changes

2023-12-15 01:44 UTC, Clansty commented on content/zh-cn/docs/hrt/Suzhou/luting/index.md
> +title: 苏州市立医院|鲁婷
真是
```suggestion
title: 苏州市立医院｜鲁婷
```

2023-12-15 01:55 UTC, Baizhi-Angelica commented on content/zh-cn/docs/hrt/Suzhou/luting/index.md
> +title: 苏州市立医院|鲁婷
我点了apply应该是改掉了吧…？

2023-12-15 01:59 UTC, Clansty approved these changes
看起来没啥问题

2023-12-16 23:48 UTC, Cryolitia approved these changes

2023-12-16 23:48 UTC, merged