📝 Update sh411 according to surgery experience
project-trans/MtF-wiki pull request #956
Opened 2023-12-17 14:22 UTC by BeiyanYunyi

批疼（恼）

2023-12-17 14:35 UTC, BeiyanYunyi commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +- 术中使用的止血材料 6216 元
医生向我表示止血材料已改进为固态。

2023-12-17 14:35 UTC, BeiyanYunyi commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +三餐分别在 06:50、11:00、16:50 推车在走廊发放。早餐 = 一个白水煮鸡蛋 +（一个馒头/包子）+（稻/粟/黑米粥）+ 咸菜（建议谨慎尝试）。午餐和晚餐的普食 = 米饭 + 青菜 + 一荤 + 一谜（一荤可能是带刺的鱼，一谜可能是鸡蛋），半流食则可能是馄饨/面条/粥，医院饮食一日价格为 30 元，禁食期间以外，无论是否食用均会收取。早餐需自备或购买碗；午餐和晚餐为铁盘盛装，吃完或没
伙食费修订为 30 元，餐车提供一次性筷子

2023-12-17 14:35 UTC, BeiyanYunyi commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +仅限一位陪护过夜，陪护椅可在晚上拉开变成陪护床，但必须在晨 6 时前收起。**仅允许陪护在手术当天起过夜，手术前不可过夜，请注意提前安排行程。**<small>整形外科禁止此前在整形外科住过院的人以陪护的形式在整形外科住院部过夜，理由是「此前有术后的人来当陪护混廉价住宿」。</small>
导致我和陪护多花了千元以上。还是别让 411 术党来陪护了，得不偿失。不过如果医生护士不认得你的陪护的话其实也还能蒙混过关。我的陪护太让人印象深刻了。

2023-12-17 14:35 UTC, BeiyanYunyi commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +同病房成员最常见的是几天换一个的来切胸的人（可能是女同、跨男或性别认同为非二元的指派女性），幸运时也可能出现一个病房三人都是 MtF。病床换人时会拉上帘子打开紫外线灯消毒，请勿直视。
AFAB 舍友们的非二元率为 20%，样本数为 10。

2023-12-17 14:35 UTC, BeiyanYunyi commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +进入第二道门后，脱干净衣服，爬到手术床上躺好（手术床又高又窄小心别摔下来），麻醉师和护士给你接各种监护，手腕插留置针。你可能会被使用七氟烷进行吸入辅助麻醉，也可能只会被使用丙泊酚注射麻醉。在前者的情况下，呼吸面罩不会和你的面部接触。麻醉师在开始麻醉前会让你闭眼深呼吸放松，此时可以把信任交给赵博和麻醉师……~~麻醉师也可能会在插好留置针后一句话没说就给你面罩里通七氟烷，七氟烷略有刺激性气味，你可能
七氟烷可见于部分患者的收费单，我这里目前有两例。大部分患者应该是没用上七氟烷的。

2023-12-17 14:35 UTC, BeiyanYunyi commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +请量力而行，循序渐进，下地后不长时间就头晕甚至失去视力都是正常的，谨防摔倒。下地可能需要一到两天的练习，当然如果你能直接跳下床整层楼乱窜我们都为你竖大拇指。在能较长时间站立行走后可多去其他病房串门，排解其他姐妹孤苦的同时锻炼行走能力。若出现流感等疾病的院内感染，请尽量待在自己的病房以减缓传播。
但我碰上的这一轮院内感染疑似是护工带来的（）

2023-12-17 14:35 UTC, BeiyanYunyi commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +请在出院前持身份证、户口本找你的主治医生核对身份信息，尤其是姓名和住址与户口本上保持一致。如需「不宜体育运动」等字样也请此时向你的主治医生提出。请仔细核对出院小结、诊断证明，确保性别鉴定写的是「生理性别为女」，将上述材料分别找末尾署名的医生签字盖章。赵博办公室张贴有吕姓公证员的联系方式，请拍照留存。前往护士站领取《三甲医院证明》。
措辞已修改

2023-12-17 14:35 UTC, BeiyanYunyi commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +阴道内部的纱布可能会在今天拆除。此时你可能会随机收获诸如「怎么这么深啊」的感叹。
这个时候听到深了挺爽的，但之后就要遭罪了

2023-12-18 04:07 UTC, Cryolitia commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +仅限一位陪护过夜，陪护椅可在晚上拉开变成陪护床，但必须在晨 6 时前收起。**仅允许陪护在手术当天起过夜，手术前不可过夜，请注意提前安排行程。**<small>整形外科禁止此前在整形外科住过院的人以陪护的形式在整形外科住院部过夜，理由是「此前有术后的人来当陪护混廉价住宿」。</small>
> 导致我和陪护多花了千元以上。还是别让 411 术党来陪护了，得不偿失。不过如果医生护士不认得你的陪护的话其实也还能蒙混过关。我的陪护太让人印象深刻了。

难蚌

2023-12-18 04:15 UTC, Cryolitia commented on .vscode/settings.json
> +    "source.fixAll": "explicit"
等会这玩意是怎么进仓库的，没gitignore吗

2023-12-18 04:15 UTC, Cryolitia commented on content/zh-cn/docs/srs/china/sh411/_index.md
> -术晨 6:30 开塞露 2 支纳肛，憋一两分钟后如厕。~~随后可以洗个热水澡，这将是你未来十余天出院前最后一次洗热水澡~~院内热水可能无限期停止供应，需自行外出洗浴。赵博会在早 8 时左右查房并确认你做手术的决心。随后你需要做的事情包括前往护士站量血压，穿上之前买的弹力袜，换上新发的病号服并去除你身上除了手腕带以外的一切物品包括内衣。
热水停止供应为什么删了

2023-12-18 04:15 UTC, Cryolitia commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +术后需要去枕平躺 6 小时。术中使用的麻醉剂和镇痛剂，以及镇痛泵中的镇痛剂均可能导致呕吐（发生率 60%，样本数为 5）。若需要呕吐请告知护工阿姨准备好塑料袋及卫生纸，将头偏向一侧吐出深绿色的胆汁。如果去枕平躺的实在太难受又没那么想吐就把枕头要回来吧。如果呕吐持续，请联系护士注射止吐药物，~~亦可考虑关闭镇痛泵。~~
```suggestion
术后需要去枕平躺 6 小时。术中使用的麻醉剂和镇痛剂，以及镇痛泵中的镇痛剂均可能导致呕吐。若需要呕吐请告知护工阿姨准备好塑料袋及卫生纸，将头偏向一侧吐出深绿色的胆汁。如果去枕平躺的实在太难受又没那么想吐就把枕头要回来吧。如果呕吐持续，请联系护士注射止吐药物，~~亦可考虑关闭镇痛泵。~~
```

2023-12-18 04:15 UTC, Cryolitia commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +从今天开始的三个晚上，你将可以每晚获得一针成分为吗啡或哌替啶（杜冷丁）的止痛针，在熄灯前或半夜实在睡不着时向护士提出即可，在臀部肌肉注射后痛觉甚至身体感觉会很快消失，然后安稳地睡个好觉。~~部分体质特殊者会出现幻觉（20%，样本数为 10）。~~
```suggestion
从今天开始的三个晚上，你将可以每晚获得一针成分为吗啡或哌替啶（杜冷丁）的止痛针，在熄灯前或半夜实在睡不着时向护士提出即可，在臀部肌肉注射后痛觉甚至身体感觉会很快消失，然后安稳地睡个好觉。~~部分体质特殊者会出现幻觉。~~
```

其实我也有233

2023-12-18 04:15 UTC, Cryolitia commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +请在出院前持身份证、户口本找你的主治医生核对身份信息，尤其是姓名和住址与户口本上保持一致。如需「不宜体育运动」等字样也请此时向你的主治医生提出。请仔细核对出院小结、诊断证明，确保性别鉴定写的是「生理性别为女」，将上述材料分别找末尾署名的医生签字盖章。赵博办公室张贴有吕姓公证员的联系方式，请拍照留存。前往护士站领取《三甲医院证明》。
```suggestion
请在出院前持身份证、户口本找你的主治医生核对身份信息，尤其是姓名和住址与户口本上保持一致。如需「不宜体育运动」等字样也请此时向你的主治医生提出。请仔细核对出院小结、诊断证明，确保性别鉴定写的是「性别为女」而不是「性别为男」，将上述材料分别找末尾署名的医生签字盖章。赵博办公室张贴有吕姓公证员的联系方式，请拍照留存。前往护士站领取《三甲医院证明》。
```

2023-12-18 11:35 UTC, BeiyanYunyi commented on content/zh-cn/docs/srs/china/sh411/_index.md
> -术晨 6:30 开塞露 2 支纳肛，憋一两分钟后如厕。~~随后可以洗个热水澡，这将是你未来十余天出院前最后一次洗热水澡~~院内热水可能无限期停止供应，需自行外出洗浴。赵博会在早 8 时左右查房并确认你做手术的决心。随后你需要做的事情包括前往护士站量血压，穿上之前买的弹力袜，换上新发的病号服并去除你身上除了手腕带以外的一切物品包括内衣。
2b44a33

2023-12-18 14:27 UTC, Cryolitia approved these changes

2023-12-18 14:28 UTC, Baizhi-Angelica commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +同病房成员最常见的是几天换一个的来切胸的人（可能是女同、跨男或性别认同为非二元的指派女性），幸运时也可能出现一个病房三人都是 MtF。病床换人时会拉上帘子打开紫外线灯消毒，请勿直视。
我感觉ftm还是要留一留，称呼兄弟或者姐妹在411很多年了吧，尊重一点（？

2023-12-18 14:33 UTC, Baizhi-Angelica requested changes

2023-12-18 14:33 UTC, Baizhi-Angelica commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +同病房成员最常见的是几天换一个的来切胸的人（可能是女同、跨男或性别认同为非二元的指派女性），幸运时也可能出现一个病房三人都是 MtF。病床换人时会拉上帘子打开紫外线灯消毒，请勿直视。
而且这个调查样本量太少了，ftm还是要留一下比较好，毕竟也可能有ftm来看我们的页面 尊重一下兄弟们也许能让他们更舒服一些（而不是“切胸的人”） 事实上我住院期间隔壁的ftm真的很好。 只是建议，也看看大家怎么说

2023-12-18 14:36 UTC, Cryolitia commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +同病房成员最常见的是几天换一个的来切胸的人（可能是女同、跨男或性别认同为非二元的指派女性），幸运时也可能出现一个病房三人都是 MtF。病床换人时会拉上帘子打开紫外线灯消毒，请勿直视。
单独写一句“住院的室友可能有非二元性别，顺弯女等各种属性，请尊重理解，不要主观判断”比较好吧

2023-12-18 18:22 UTC, Clansty commented
切胸也不一定是 ftm 吧，万一是 cisf 不喜欢或者 detrans 的 ex mtf（x

2023-12-18 22:46 UTC, Baizhi-Angelica commented
> 切胸也不一定是 ftm 吧，万一是 cisf 不喜欢或者 detrans 的 ex mtf（x

总之还是尽可能包容一点友善一点

2023-12-19 02:58 UTC, BeiyanYunyi commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +同病房成员最常见的是几天换一个的来切胸的人（可能是女同、跨男或性别认同为非二元的指派女性），幸运时也可能出现一个病房三人都是 MtF。病床换人时会拉上帘子打开紫外线灯消毒，请勿直视。
不是不留跨男（我写了跨男），而是拓展了切胸的范围，因为我遇到的来切胸的其他性少数真的不少。所以我的表述是“可能是跨男、非二元和女同”

2023-12-19 07:42 UTC, Baizhi-Angelica commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +同病房成员最常见的是几天换一个的来切胸的人（可能是女同、跨男或性别认同为非二元的指派女性），幸运时也可能出现一个病房三人都是 MtF。病床换人时会拉上帘子打开紫外线灯消毒，请勿直视。
抱歉我不知道怎么留建议修改，但感觉“住院的室友可能有非二元性别，顺弯女等各种属性，请尊重理解，不要主观判断”会更友善一点点，不知道大家意见怎么样

2023-12-19 07:44 UTC, Baizhi-Angelica commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +同病房成员最常见的是几天换一个的来切胸的人（可能是女同、跨男或性别认同为非二元的指派女性），幸运时也可能出现一个病房三人都是 MtF。病床换人时会拉上帘子打开紫外线灯消毒，请勿直视。
因为你前后还是要尽量一致，这里写mtf后面写跨男，让人有点摸不着头脑，也可以前面写跨女后面写跨男，或者就干脆把跨男改成ftm也许更好。

2023-12-19 11:45 UTC, BeiyanYunyi commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +同病房成员最常见的是几天换一个的来切胸的人（可能是女同、跨男或性别认同为非二元的指派女性），幸运时也可能出现一个病房三人都是 MtF。病床换人时会拉上帘子打开紫外线灯消毒，请勿直视。
0211ece 如何

2023-12-19 12:10 UTC, Baizhi-Angelica commented on content/zh-cn/docs/srs/china/sh411/_index.md
> +同病房成员最常见的是几天换一个的来切胸的人（可能是女同、跨男或性别认同为非二元的指派女性），幸运时也可能出现一个病房三人都是 MtF。病床换人时会拉上帘子打开紫外线灯消毒，请勿直视。
> [0211ece](https://github.com/project-trans/MtF-wiki/commit/0211ece6dd9019acd6e657c3c06dc0193dea9838) 如何

滋瓷！！

2023-12-19 12:12 UTC, Baizhi-Angelica approved these changes
滋瓷

2023-12-25 01:30 UTC, merged