Add packaging desc for progynova germany and progynova india
project-trans/MtF-wiki pull request #966
Opened 2024-01-14 08:02 UTC by Christalise

Currently, there are several individual pharmaceutical sellers selling Indian Progynova as German Progynova and providing others with incorrect information. 

I believe it is necessary to include information about both Indian Progynova and German Progynova in the wiki.

2024-01-14 08:04 UTC, clansty commented on content/zh-cn/docs/medicine/estrogen/estradiol-valerate/index.md
> +[^6]: Jenapharm GmbH & Co KG. Gebrauchsinformation: Progynova&reg; 21 [EB/OL]. 2023-08. <https://www.jenapharm.de/download/14/116/2486.pdf>（德文）
这里改了啥，行结尾符嘛

2024-01-14 08:05 UTC, Christalise commented on content/zh-cn/docs/medicine/estrogen/estradiol-valerate/index.md
> +[^6]: Jenapharm GmbH & Co KG. Gebrauchsinformation: Progynova&reg; 21 [EB/OL]. 2023-08. <https://www.jenapharm.de/download/14/116/2486.pdf>（德文）
我不知道 我没有改这里任何东西 可能是diff判断错了? 两个字符串是一样的

2024-01-14 08:36 UTC, Christalise commented on content/zh-cn/docs/medicine/estrogen/estradiol-valerate/index.md
> +[^6]: Jenapharm GmbH & Co KG. Gebrauchsinformation: Progynova&reg; 21 [EB/OL]. 2023-08. <https://www.jenapharm.de/download/14/116/2486.pdf>（德文）
fixed

2024-01-15 12:12 UTC, Bersella-AI requested changes
严格来说，“补佳乐 Progynova”品牌归属于德国拜耳，而拜耳在某些地区会和其它厂家合作制售药品：例如，在中国大陆销售的“补佳乐”由法国公司（DELPHARM Lille S.A.S.）生产，而在本例中，“印补”由当地公司 [Zydus Healthcare Limited](https://www.zydushealthcare.com/) 生产，可能是出于合规要求；但无论如何，生产标准和产品性状是和拜耳原厂一致的，在印度[当地网上药店](https://www.1mg.com/drugs/progynova-2mg-tablet-8117)中可见其为白色圆形包衣片，符合原厂特征，疗效应与原厂产品一致。综上，卖方将任一地区分销的“补佳乐”称为“德补”并不违法，但与商业道德相悖；而我们作为中立信息平台不会参与任何商业纠纷，也不对任何商业行为置评，此观点不能代表我们对这类行为之立场，故应审慎登载，参考如下。

2024-01-15 12:35 UTC, Christalise commented on content/zh-cn/docs/medicine/estrogen/estradiol-valerate/index.md
> +{{< /notice >}}
行，改完了，谢谢 Bersella-AI ~

2024-01-17 13:32 UTC, Bersella-AI approved these changes

2024-01-19 03:39 UTC, clansty approved these changes

2024-01-19 03:42 UTC, merged