达芬奇机器人使用Nix！
project-trans/MtF-wiki pull request #991
Opened 2024-03-17 14:58 UTC by Cryolitia

2024-03-17 16:56 UTC, clansty commented
草，夹带私货是吧

2024-03-17 16:57 UTC, clansty requested changes

2024-03-17 16:57 UTC, clansty commented on content/zh-cn/docs/srs/china/xa-imc/index.md
> +> 达芬奇机器人使用极其先进的可复现的[Nix](https://nixos.org/)构建系统[^2]，~~不来试一试吗~~。
```suggestion
> 达芬奇机器人使用极其先进的可复现的 [Nix](https://nixos.org/) 构建系统[^2]，~~不来试一试吗~~。
```

2024-03-17 18:12 UTC, clansty approved these changes

2024-03-17 21:14 UTC, clansty approved these changes

2024-03-18 09:42 UTC, BeiyanYunyi approved these changes

2024-03-19 02:59 UTC, merged